SAK-46665 Scheduler: Filter Events page not displaying, stack traces on the server
sakaiproject/sakai pull request #10078
Opened 2021-12-10 09:08 UTC by ropemar

There was a problem with the migration of this tool to JSF2, since the tag <sakai:script> wasn't recognized. That was the reason of the crash and the exceptions being printed on the console. I removed those unnecessary scripts and changed the input date fields of the form to the standard input type "datetime-local". Now we receive that data on the bean manager to configure the filters properly.

2021-12-14 15:31 UTC, mpellicer requested changes

2021-12-14 15:31 UTC, mpellicer commented on jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java
> +           if (beforeText != null && !beforeText.isBlank()) {
Use StringUtils.isNotBlank(beforeText)

2021-12-14 15:31 UTC, mpellicer commented on jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java
> +           if (afterText != null && !afterText.isBlank()) {
Same as before, use StringUtils.isNotBlank!

2021-12-14 15:32 UTC, mpellicer commented
I'd like to discuss this in the core team call, I discussed with @ropemar the user of the datetime-local inputs and we like the idea, I think it's better to use native HTML5 input type instead of the jQuery datepicker.

2021-12-14 15:33 UTC, mpellicer commented
https://caniuse.com/?search=datetime-local

2021-12-14 15:37 UTC, ottenhoff commented
I also would like to see us move more to datetime-local.  We can do this via our lang-datepicker.js though. We can use the native where supported and use the jquery datepicker elsewhere.

2021-12-21 16:48 UTC, mpellicer approved these changes

2021-12-21 16:48 UTC, merged