SAK-45051 Add Gradebook items to Tasks widget
sakaiproject/sakai pull request #10139
Opened 2022-01-10 10:41 UTC by ropemar

This pull request includes modifications in edu-services to implement an entity to GradebookAssignments, since it was required on task creation to have a reference to the items on the gradebook. The gradebook was also modified to have a new checkbox option when creating gradebook items in order to create new tasks for the widget. Tasks created within the gradebook will be also updaded or deleted when corresponding gradebook items do so.

2022-01-21 14:20 UTC, ottenhoff commented on edu-services/gradebook-service/api/pom.xml
> +    </dependency>
duplicated dependency?

2022-01-25 08:16 UTC, ropemar commented on edu-services/gradebook-service/api/pom.xml
> +    </dependency>
Thanks for noticing it!

2022-01-25 13:20 UTC, adrianfish requested changes
I like how you've taken the approach of wrapping Assignment with a new class, rather than trying to change Assignment directly. However, you're not using entitymanager and entityproducer correctly. You should not need a method on the grading service to retrieve the entity. Entities should come from the entitymanager when given a reference. Also, you should not need to pass services to your new entity class just so it can set up some internal state - just pass that state directly.

This is a tough area of the Sakai codebase. I think you've made a good attempt at working your way around this code but it is a lot to ask for expecting you to get it right first time. If you need some more help, just ask.

2022-01-25 13:20 UTC, adrianfish commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
> +	private CheckBox createtask;
Use camel case for createtask

2022-01-25 13:20 UTC, adrianfish commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
> +		final WebMarkupContainer createtaskLabel = new WebMarkupContainer("createtaskLabel");
I'd use camel case here, createTaskLabel.

2022-01-31 11:02 UTC, ropemar commented
Once I've understood how entities and references work, I've simplified this PR a little bit.

2022-02-01 08:38 UTC, mpellicer approved these changes

2022-02-01 08:38 UTC, merged

2022-03-31 21:47 UTC, ern commented
@mpellicer when you merge these PR's please cleanup the commit messages, thanks!