SAK-46781 Added js log message explaining the 404 error
sakaiproject/sakai pull request #10171
Opened 2022-01-18 17:22 UTC by adrianfish

https://sakaiproject.atlassian.net/browse/SAK-46781

This error is displayed by a browser when a 404 is received. Rubrics
makes a get request for the returned evaluation backup copy when saving,
and it's perfectly valid for this to return a 404. The code handles the
404 returned, but the browser also prints the 404 "error" to the
console.

2022-01-19 16:11 UTC, ern approved these changes

2022-01-20 09:04 UTC, mpellicer requested changes
Hey Adrian, not good from the L10N perspective, the text is hardcoded and needs localization.

2022-01-20 10:15 UTC, adrianfish commented
@mpellicer Sorry, should have thought of that. I'll add it to the i18n bundle.

2022-01-20 10:21 UTC, mpellicer commented
No worries Adrian, if it's for DEV purposes it's fine, but if some real user can read it, it should be in their language, this is super minor considering it should be an advanced user.

2022-01-20 14:29 UTC, mpellicer approved these changes

2022-01-25 11:12 UTC, merged