SAK-45221 Assignments add content review score to Sakai Grader
sakaiproject/sakai pull request #10226
Opened 2022-02-05 02:25 UTC by davidpbauer

Add a section to Sakai Grader that will show the content review results
in the same way they are shown on the classic grader thus preventing
instructors from switching back to classic or using the list view to
see them.

2022-02-07 16:40 UTC, ottenhoff commented
Seems like failure on npm run eslint

2022-02-07 16:41 UTC, ottenhoff commented on webcomponents/tool/src/main/frontend/js/grader/submission.js
> +      for(var count=1; init.properties["originalityLink"+count]!=null; count++){
this should be prob be a let instead of var?

and maybe a different variable name instead of count?

2022-02-07 18:26 UTC, davidpbauer commented
Thanks for the review! @jkozar2 authored this, so I'll see if he wants to make changes or would rather I just jump in myself.

2022-02-07 18:38 UTC, adrianfish requested changes

2022-02-07 18:38 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/grader/submission.js
> +        var originalityDataNow = [];
```suggestion
        const originalityDataNow = [];
```

2022-02-07 18:38 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/grader/submission.js
> +        if(init.properties["originalityInline"+count] ==='true'){
```suggestion
        if (init.properties[`originalityInline${count}`] === 'true') {
```

2022-02-08 15:25 UTC, jkozar2 commented
I'll be happy to make these changes, but it will be a while because I have to get a working 23 environment set up first. Thanks for the review!

2022-02-09 19:59 UTC, davidpbauer commented
I think I've caught all of the requested changes, but let me know if there's anything else.

2022-02-11 18:55 UTC, adrianfish commented
I'd move the originality constants object to a static member of Submission. No point recreating that object each time. So, on the lines before the customElement.define piece, you'd just add something like:
Submission.originalityConstants = {
...
};

2022-02-11 18:57 UTC, adrianfish commented
Or, if you feel like they may be used elsewhere, you could put them in their own js module, originality-constants.js, in the grader folder.

export const originalityConstants = {
...
};

in Submission.js

import { originalityConstants } from "./originality-constants.js";

2022-02-25 19:40 UTC, davidpbauer commented
I've moved originality constants. Adrian, can you take another look?

2022-03-28 10:32 UTC, adrianfish requested changes
can we change all the camel case ids and classes to be hyphenated, like the rest of the code? Using hyphenated ids and classes differentiates them from js variable names where we use camel case.

2022-04-20 12:32 UTC, adrianfish approved these changes

2022-04-20 12:33 UTC, merged