TRINITY-54: Create api endpoints for Assignments and AssignmentSubmissions
sakaiproject/sakai pull request #10315
Opened 2022-03-03 12:32 UTC by stetsche

Added api endpoints for Assignments and AssignmentSubmissions

Removed some unused constants in AssignmentConstants

2022-03-03 14:35 UTC, adrianfish requested changes
Some small stuff

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +        return beanList;
```suggestion
        return assignmentService.getAssignmentsForContext(siteId).stream().map(assignment -> {
            AssignmentRestBean bean = new AssignmentRestBean(assignment);
            bean.setStatus(assignmentService.getAssignmentStatus(assignment.getId()));
            bean.setScale(assignmentService.getScaleDisplay(assignment.getId()));
            bean.setAccess(assignmentService.getAccessDisplay(assignment.getId()));
            String assignmentReference = assignmentService.assignmentReference(siteId, assignment.getId());
            bean.setTotalSubmissions(assignmentService.countSubmissions(assignmentReference, null));
            bean.setNewSubmissions(assignmentService.countSubmissions(assignmentReference, false));
            return bean;
        }).collect(Collectors.toList());
```

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +    @GetMapping(value = "/assignments/{assignmentId}/submissions", produces = MediaType.APPLICATION_JSON_VALUE)
I think you should stick to /sites/{siteId}/assignments/{assignmentId}/submissions. I know it's a bit longer, but it's consistent with other parts of the webapi. But, I'm open to discussion.

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +            if (assignment == null | assignment.getDeleted()) {
Binary OR ??

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +            if (assignment == null | assignment.getDeleted()) {
I don't think you intended that!

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +            if (assignment == null | assignment.getDeleted()) {
although, same result

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +            List<AssignmentSubmissionRestBean> beanList = userDirectoryService.getUsers(userIds).stream().map(user -> {
just return the list straight off, no variable needed

2022-03-03 14:35 UTC, adrianfish commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +	@Autowired
tabbing

2022-03-04 19:28 UTC, profmikegreene commented
I didn't get a chance to look at this yesterday, does it need a rebase or something? Is it supposed to be this many commits/files @stetsche

2022-03-08 07:29 UTC, stetsche commented
thanks, fixed it

2022-03-08 10:07 UTC, mpellicer commented
Is the Java build broken?

2022-03-08 10:14 UTC, stetsche commented
the build here is failing in library, but yes actually there is a problem in webapi too

2022-03-08 10:20 UTC, stetsche commented
> Is the Java build broken?
Assignments and webapi are building fine. It is failing in library.

2022-03-15 13:37 UTC, ern commented on webapi/src/main/java/org/sakaiproject/webapi/beans/AssignmentRestBean.java
> +        id = assignment.getId();
Would add a Objects.requireNonNull assignment check

2022-03-15 13:55 UTC, ern commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/AssignmentsController.java
> +    public List<AssignmentRestBean> getSiteAssignments(@PathVariable String siteId) {
return a Collection vs List

2022-03-15 13:56 UTC, ern commented on webapi/src/main/java/org/sakaiproject/webapi/beans/AssignmentSubmissionRestBean.java
> +@Getter
Maybe use @Data or @EqualsAndHashcode and set the field to be the id for the equality check

2022-03-15 13:57 UTC, ern commented on webapi/src/main/java/org/sakaiproject/webapi/beans/AssignmentSubmissionRestBean.java
> +        Assignment assignment = assignmentSubmission.getAssignment();
Add a check for a null assignmentSubmission and check for a empty id (maybe StringUtils.isBlank)

2022-03-15 13:59 UTC, profmikegreene reviewed
Looks good for what trinity project needs. Thanks!

2022-03-16 08:57 UTC, mpellicer approved these changes

2022-03-16 08:57 UTC, merged