SAK-46725 Resources: Plus sign should be in Other Sites folders with tree view available
sakaiproject/sakai pull request #10323
Opened 2022-03-07 11:48 UTC by josecebe

2022-03-07 12:33 UTC, feralvarez95 approved these changes
I have tested in my local instance, now looks fine!

![image](https://user-images.githubusercontent.com/19774177/157035246-db531609-8651-468a-b5d0-e51599ddc111.png)

2022-03-07 15:01 UTC, jesusmmp approved these changes
LGTM!

2022-03-08 15:48 UTC, fostersdesign requested changes

2022-03-08 15:48 UTC, fostersdesign commented on library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
> +			right: 4px;
Please use $standard-space:

```suggestion
			right: $standard-space;
```

2022-03-08 15:48 UTC, fostersdesign commented on library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
> +			right: 4px;
Please use $standard-space:

```suggestion
			right: $standard-space;
```

2022-03-09 12:37 UTC, mpellicer approved these changes

2022-03-09 12:37 UTC, mpellicer commented
Thanks for the review @fostersdesign and good job @josecebe

2022-03-09 12:37 UTC, merged