SAK-43763 Date Manager-T&Q: Only allow feedback dates to updated if there are no exceptions
sakaiproject/sakai pull request #10373
Opened 2022-03-28 19:18 UTC by gwickram

https://sakaiproject.atlassian.net/browse/SAK-43763

2022-04-19 15:01 UTC, ern commented on site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
> +import org.sakaiproject.tool.assessment.facade.*;
Please don't use glob imports

2022-04-19 15:04 UTC, ottenhoff requested changes
Reviewed on core call: please make sure text is internationalized so it can be translated

2022-04-21 21:24 UTC, gwickram commented
The changes were added. thanks.

2022-04-21 22:40 UTC, ottenhoff commented on site-manage/datemanager/tool/src/main/resources/static/js/initDatePicker.js
> +			   $td.append('<a tabindex="0" style="cursor: pointer; text-decoration: none;" class="fa fa-info-circle fa-lg" data-toggle="popover" data-trigger="focus" data-container="body" data-placement="auto
this is the text we need internationalized

2022-11-11 16:37 UTC, ern commented
Moving this to a draft until the conflicts are resolved

2025-11-11 02:44 UTC, closed without merging