SAK-45052 Dashboard and Tests & Quizzes: Always create a task item when publishing assessments.
sakaiproject/sakai pull request #10384
Opened 2022-03-31 13:41 UTC by druiz309

The specs on this Jira never mentioned for conditional creation of tasks on the dashboard. Consequently, radio buttons and some methods have been removed. Currently, tests are automatically created, updated and removed. Anyone can also see tests in the tasks widget in the dashboard.

2022-03-31 15:45 UTC, mpellicer requested changes
Revert format changes please, focus only on removing the checkbox associated to the task.

2022-03-31 15:45 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
> + * <p>
Revert these changes

2022-03-31 15:45 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
> +        implements ActionListener {
Revert these changes

2022-03-31 15:47 UTC, mpellicer requested changes

2022-04-01 09:14 UTC, druiz309 commented
I have just made the changes @mpellicer

2022-04-01 10:34 UTC, mpellicer approved these changes

2022-04-01 10:34 UTC, mpellicer commented
Good job @druiz309 !

2022-04-01 10:39 UTC, mpellicer commented
@druiz309 Could you change the commit message to this? 

'SAK-45052 Dashboard and Tests & Quizzes: Always create a task item when publishing assessments.'

2022-04-01 10:40 UTC, mpellicer commented
I believe we will recover these changes in the future if the spec advances, I like the idea of controlling the task item by a checkbox but at the same time is more work for the instructor, as it's not clear in the specs what the community wants let's simplify the use cases.

2022-04-01 11:07 UTC, druiz309 commented
> @druiz309 Could you change the commit message to this?
> 
> 'SAK-45052 Dashboard and Tests & Quizzes: Always create a task item when publishing assessments.'

I have changed the commit message @mpellicer

2022-04-01 11:12 UTC, mpellicer approved these changes

2022-04-01 12:18 UTC, merged