TRI-39 first working prototype of sui-table
sakaiproject/sakai pull request #10397
Opened 2022-04-05 12:30 UTC by profmikegreene

…tation (#9973)

Co-authored-by: Shawn <shawn.foster@uwo.ca>

2022-04-21 02:59 UTC, fostersdesign approved these changes
Thank you for making those changes. Looks good to me!

2022-04-21 03:01 UTC, fostersdesign commented
@adrianfish - can you take a look at this for us too, please? Especially the new SuiTable.js and the changes to webcomponents. Please provide any suggestions or comments.

2022-05-01 18:00 UTC, adrianfish requested changes
I've added a couple of commits. One of the commits is to  remove the debug stuff as I don't reckon you need that. Just add console.log as and when you need them. My opinion anyway, feel free to leave them in. Just ignore my stuff if you feel like it. The only thing I'd recommend checking is the use of attributes which could belong to the enclosing tag and the stuff inside.

2022-05-03 12:40 UTC, profmikegreene commented on webcomponents/tool/src/main/frontend/js/sakai-ui/sui-button/sui-button.js
>    LitElement,
I'm a big fan of configurable code formatting. Most things don't matter much to me, I just want to be able to run a command or have it auto formatted on a git hook and not have to think about it. Prettier is pretty common on the frontend and is what this was run through. I'd be happy to add a config to the webcomponents project and configure it to our liking, just didn't get to that yet.

2022-05-04 23:50 UTC, profmikegreene commented on webcomponents/tool/src/main/frontend/js/sakai-ui/sui-button/sui-button.js
> +      ariaLabel: { type: String },
I changed all the valid attributes that were being passed to inner dom elements to custom attributes as discussed on the 05/04/2022 call.

2022-05-05 00:21 UTC, profmikegreene commented on webcomponents/tool/src/main/frontend/js/sakai-ui/sui-table/src/SuiTable.js
> +    this.rows = await this.fetchRows();
I agree but I don't have the knowledge or time to adjust that right now. I put a TODO there in the latest commit and will create a JIRA for it.

2022-05-05 00:45 UTC, profmikegreene commented on webcomponents/tool/src/main/frontend/js/sakai-ui/sui-button/sui-button.js
> +      onclick: { type: String },
mostly was a placeholder for anticipating non-href buttons, but since we don't have any of those yet, I removed it.

2022-05-05 03:05 UTC, fostersdesign approved these changes
Looks much better! Thanks, @profmikegreene .

2022-05-05 03:06 UTC, fostersdesign commented
@adrianfish , would you like to take another look at the changes before we merge it?

2022-05-05 18:09 UTC, adrianfish approved these changes
Looks good to me.

2022-05-05 19:04 UTC, merged

2022-05-05 19:04 UTC, fostersdesign commented
Thanks, @adrianfish. Merged.