SAK-47235 Show student answer date when grading lessons questions
sakaiproject/sakai pull request #10500
Opened 2022-05-02 11:36 UTC by PabloArrz

In lessons tool, when an instructor goes to grade students submissions on a lessons question, it would be nice to add the student answer date.

2022-05-02 11:43 UTC, josecebe requested changes

2022-05-02 11:43 UTC, josecebe commented on lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
> +			UIOutput.make(tofill, "last-row-grade");
Fix tabs

2022-05-02 11:43 UTC, josecebe commented on lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
> +				UIOutput.make(branch, "student-date", userTimeService.dateTimeFormat(user.response.getTimeAnswered().toInstant(), null, null));
fix tabs

2022-05-02 11:43 UTC, josecebe commented on lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
> +
Remove empty line

2022-05-02 11:43 UTC, josecebe commented on lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
> +
fix tabs

2022-05-02 11:43 UTC, josecebe commented on lessonbuilder/tool/src/resources/messages_es.properties
> +simplepage.grading-date=Fecha de envío
Use unicode

2022-05-02 12:39 UTC, PabloArrz commented
@josecebe I have apply the changes.

2022-05-02 12:50 UTC, ottenhoff approved these changes

2022-05-02 13:18 UTC, josecebe commented
Good job @PabloArrz , LGTM!

2022-05-03 07:46 UTC, josecebe approved these changes

2022-05-03 08:18 UTC, mpellicer approved these changes
Clean, good job guys @PabloArrz and @josecebe

2022-05-03 08:18 UTC, merged