SAK-43768 SAMIGO: Randomize question pools with option: A student's questions are randomized once for all submissions
sakaiproject/sakai pull request #10522
Opened 2022-05-06 10:49 UTC by PabloArrz

https://sakaiproject.atlassian.net/browse/SAK-43768

2022-05-06 11:40 UTC, mpellicer requested changes
This PR could introduce backward compatibility issues, @vacercon may expand on that.

2022-05-23 09:43 UTC, mpellicer requested changes
Just improve the documentation and include brackets.

2022-05-23 09:43 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
> +	  if (StringUtils.isNotBlank(sectionRandomizationSeed)) seed += Long.parseLong(sectionRandomizationSeed);
Please, include a comment.

// If the section has a previous seed we must use it to use the same order.

Also use brackets here:

if (StringUtils.isNotBlank(sectionRandomizationSeed)) {
   seed += Long.parseLong(sectionRandomizationSeed);
}

2022-05-23 09:43 UTC, mpellicer commented on samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
> +		h.add(new PublishedSectionMetaData(publishedSection, SectionDataIfc.RANDOMIZATION_SEED, String.valueOf(UUID.randomUUID().hashCode())));
Please include this comment:

// Persist the random seed in the section to use it and preserve the order.

2022-05-23 09:43 UTC, mpellicer commented
Well done @PabloArrz ! Clean and neat.

2022-05-23 10:06 UTC, PabloArrz commented
@mpellicer I have improved the documentation and include the brackets.

2022-05-23 10:10 UTC, mpellicer commented
@josecebe WDYT? Ready to go?

2022-05-23 10:11 UTC, mpellicer approved these changes

2022-05-23 11:07 UTC, josecebe commented
> @josecebe WDYT? Ready to go?

It works nice, but we will test it deeply after it gets merged, I saw there are more seed references in the code, but maybe is not necessary to modify those seeds to keep it working properly.

2022-05-23 11:16 UTC, mpellicer commented
Thanks for the feedback

2022-05-23 11:17 UTC, merged

2022-05-24 15:12 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
> +	  }
@josecebe Could you clarify this? Thanks

2022-05-30 16:31 UTC, bbailla2 commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
> +	  }
Here's my understanding of the intention:
When a new Section is created, then we insert a seed into the section metadata. This particular snippet checks for the existence of a randomization seed in the metadata, and if the result is non-blank, then it's added to the seed - this bit looks fine to me