SAK-46657 provide better error message when points dont match categor…
sakaiproject/sakai pull request #10556
Opened 2022-05-16 14:37 UTC by ottenhoff

…y rules

2022-05-17 12:04 UTC, adrianfish requested changes

2022-05-17 12:04 UTC, adrianfish commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
> +gradebook_exception_category_invalid=Warning: all items in a Gradebook Category using drop lowest or drop highest must have matching point values. Either edit the assessmet to alter the point values
```suggestion
gradebook_exception_category_invalid=Warning: all items in a Gradebook Category using drop lowest or drop highest must have matching point values. Either edit the assessment to alter the point values or choose a different category.
```

2022-05-17 12:04 UTC, adrianfish commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
> +		String err=(String)ContextUtil.getLocalizedString("org.sakaiproject.tool.assessment.bundle.AuthorMessages",
```suggestion
		String err = (String)ContextUtil.getLocalizedString("org.sakaiproject.tool.assessment.bundle.AuthorMessages",
```

2022-05-17 13:35 UTC, ottenhoff commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
> +gradebook_exception_category_invalid=Warning: all items in a Gradebook Category using drop lowest or drop highest must have matching point values. Either edit the assessmet to alter the point values
nice

2022-05-23 16:57 UTC, ern commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
> +		log.warn(gbe.getMessage());
More informative log message?
```suggestion
		log.warn("Incorrect gradebook category settings: {}", gbe.toString());
```

2022-06-09 09:44 UTC, adrianfish approved these changes

2022-06-09 17:17 UTC, merged