SAK-47679 Update Passay 1.6.2 & antisamy 1.7.0
sakaiproject/sakai pull request #10794
Opened 2022-08-12 06:06 UTC by axxter99

2022-08-12 12:56 UTC, bjones86 approved these changes

2022-08-18 09:46 UTC, mpellicer approved these changes

2022-08-18 09:54 UTC, mpellicer requested changes
Tests are failing, could you maybe rebase the branch? Thanks!

2022-08-18 12:56 UTC, closed without merging

2022-08-18 13:06 UTC, axxter99 commented
#10804