SAK-47878 - Improve the configuration and launch experience for sakai.web.168 tool
sakaiproject/sakai pull request #10891
Opened 2022-09-25 00:28 UTC by csev

Adrian - this makes a new web component for the sakai-lti-popup and adds some features to the sakai-lti-iframe code to cope with bad urls.   But there is a TODO that I could not make work because the then() clause does not finish before the constructor finishes :(

2022-09-26 13:49 UTC, csev commented
So @adrianfish  I figured out the then() syntax and finished this up - it is ready for review.

2022-09-26 18:59 UTC, adrianfish requested changes
A few changes needed, not much :)

2022-09-26 18:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js
> +      console.log('elem', elem);
I'd go for log.debug here.

2022-09-26 18:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js
> +      console.log("timeout check", elem.randomId, elem.launchUrl);
Again, I'd use log.debug, try and keep the normal console a bit less cluttered.

2022-09-26 18:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js
> +      const mybutton = $("#sakai-lti-button-" + elem.randomId);
```suggestion
      const myframe = document.getElementById(`sakai-lti-iframe-${elem.randomId}`);
      const mybutton = document.getElementById(`sakai-lti-button-${elem.randomId}`);
```

2022-09-26 18:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js
> +        const windowLoc = String(window.location);
```suggestion
        const windowLoc = window.location.href;
```

2022-09-26 18:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js
> +        Array.prototype.forEach.call(document.getElementsByTagName('iframe'), element => {
```suggestion
        Array.from(document.getElementsByTagName('iframe')).forEach(element => {
```

2022-09-26 18:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-lti-popup.js
> +    onclick="
You should use the @click handler. Just create a function in your class with all the stuff in the onclick handler, then add @click to the button tag. So, you'd add @click=${this.handlePopup} to the tag.

2022-09-26 23:30 UTC, csev commented
Hey @adrianfish - I think I got them all - thanks for the @click pointer.  Elegant.

2022-09-27 15:37 UTC, adrianfish approved these changes
GTG :)

2022-09-27 15:39 UTC, merged