SAK-48113: PA System: B-5 update
sakaiproject/sakai pull request #11059
Opened 2022-11-29 13:51 UTC by kunaljaykam

https://sakaiproject.atlassian.net/browse/SAK-48113

2022-11-29 15:02 UTC, adrianfish requested changes
You've left a few typos in there, and I added a few js changes.

2022-11-29 15:02 UTC, adrianfish commented on pasystem/pasystem-tool/tool/src/webapp/scripts/pasystem-tool.js
> +          var bsModal = new bootstrap.Modal(modal_id);
```suggestion
          const modalId = document.getElementById("pasystemDeleteConfirmationModal");
          (new bootstrap.Modal(modalId)).show();
```

2022-11-29 15:02 UTC, adrianfish commented on pasystem/pasystem-tool/tool/src/webapp/scripts/pasystem-tool.js
> +          bsModal.show();
```suggestion
```

2022-11-29 15:26 UTC, kunaljaykam commented on library/src/skins/default/src/sass/base/_icons.scss
> +    sakai-delete-icon : bi-trash,
You are right, We shouldn't. Thanks

2022-11-30 09:39 UTC, adrianfish approved these changes

2022-11-30 09:40 UTC, merged