SAK-48138 - Duplicate id="portal-notifications-indicator" in the Trinity portal markup
sakaiproject/sakai pull request #11071
Opened 2022-12-01 14:08 UTC by csev

2022-12-01 14:12 UTC, kunaljaykam approved these changes

2022-12-01 16:26 UTC, adrianfish requested changes
You can just remove the id. It's not used anywhere. The important one is the class.

2022-12-02 22:16 UTC, adrianfish commented on portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
> +        <span id="portal-notifications-indicator-account-nav" class="portal-notifications-indicator p-1 bg-danger rounded-circle" style="display: none">
```suggestion
        <span class="portal-notifications-indicator p-1 bg-danger rounded-circle" style="display: none">
```

2022-12-02 22:16 UTC, adrianfish commented on portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeMobileFooter.vm
> +        <span id="portal-notifications-indicator-mobile-footer" class="portal-notifications-indicator p-1 bg-danger rounded-circle" style="display: none">
```suggestion
        <span class="portal-notifications-indicator p-1 bg-danger rounded-circle" style="display: none">
```

2022-12-02 22:17 UTC, adrianfish approved these changes

2022-12-03 13:40 UTC, merged