S2U-5.1.1.6 Tests & Quizzes: Ability to preview calculated questions in question pools
sakaiproject/sakai pull request #11193
Opened 2023-01-22 12:07 UTC by jesusmmp

https://sakaiproject.atlassian.net/browse/S2U-10

- Adding incorrect feedback on the preview
- Fixing some regression caused by: https://github.com/sakaiproject/sakai/pull/6139

Result:

![image](https://user-images.githubusercontent.com/15141743/213914920-cff759c7-dee9-4043-b02c-5ee447a2725f.png)

2023-01-23 07:32 UTC, bgarciaentornos commented
It seems like this PR is incorporating previous commits? Also it appears linked to the wrong jira.

2023-01-24 09:11 UTC, mpellicer commented on samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
> +<script>
@jesusmmp

Could we implement this avoiding jQuery? jQuery could be removed in the future and I prefer using vanilla JS.

2023-01-24 09:12 UTC, mpellicer requested changes
It looks great @jesusmmp thank you very much.

Just one comment about the JS snippet.

2023-01-25 16:38 UTC, mpellicer approved these changes

2023-01-25 16:38 UTC, mpellicer commented
Awesome!

2023-01-25 16:39 UTC, merged