Bootstrap 5 upgrade: Remove Bootstrap 3 classes and replace Bootstrap form in Rubrics
sakaiproject/sakai pull request #11217
Opened 2023-01-31 20:24 UTC by jkozar2

Contribution to the ongoing Bootstrap 3 to 5 project: https://docs.google.com/document/d/1HCNLBswh5guaPLAEPkKnuadHBy8HKh_q3D5q-cAeUA8
I replaced a number of classes as specified in the document, and found a form that does validation and "successful save" notification based on Bootstrap 3 classes. I replaced them with custom styling and JQuery methods.

2023-02-02 07:12 UTC, kunaljaykam commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
> +            <div class="sak-banner-success" style="display:none">
Was it necessary to remove the class `d-none`?

2023-02-14 15:43 UTC, adrianfish requested changes

2023-02-14 15:51 UTC, ern commented
Joe can you add the SAK ticket for this in title

2023-03-09 21:18 UTC, jkozar2 commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
> +            $(saveSuccessLbl).show();
I had done this to replicate the fade-out behavior that the existing Bootstrap stuff was doing. JQuery was the best other option I could come up with. I then considered trying to do it manually somehow, but on my latest change I just got rid of the fade and have it disappearing instantly after 5 seconds. So if we're ok without the fade this is taken care of!

2023-03-21 15:35 UTC, jkozar2 commented
I couldn't find a SAK ticket number to add to this, either a master ticket for the project or a Rubrics one. Should I make one, or is there a proper ticket for this I'm just not finding?

2023-03-21 20:51 UTC, jkozar2 commented
Made this ticket for tracking the issue:
https://sakaiproject.atlassian.net/browse/SAK-48653

2023-03-28 15:32 UTC, kunaljaykam approved these changes

2023-03-28 15:33 UTC, merged