SAK-48533 - Add explicit depends-on to beans that depend on localization properties
sakaiproject/sakai pull request #11295
Opened 2023-02-25 16:21 UTC by jonespm

These are all the ones I saw. Perhaps there's a better way to do this but this at least verified that things were working and the load order is correct.

2023-02-27 15:04 UTC, ottenhoff approved these changes
Makes sense to me. @ern?

2023-02-28 20:06 UTC, ern commented
I am looking at what's going on with this

2023-02-28 20:09 UTC, jonespm commented
This isn't required, but if this was here it wouldn have been more obvious that this was broken when this component deployment was changed. 

All of these files depend on loading this class locally and some of these are used by this service. Actually it looks like it's just TypeProperties and not ContentTypeProperties. 

```
content-types/src/java/org/sakaiproject/content/types/FolderType.java
81:	private static final String DEFAULT_RESOURCECLASS = "org.sakaiproject.localization.util.TypeProperties";

content-types/src/java/org/sakaiproject/content/types/HtmlDocumentType.java
56:	private static final String DEFAULT_RESOURCECLASS = "org.sakaiproject.localization.util.TypeProperties";

content-types/src/java/org/sakaiproject/content/types/FileUploadType.java
71:	private static final String DEFAULT_RESOURCECLASS = "org.sakaiproject.localization.util.TypeProperties";

content-types/src/java/org/sakaiproject/content/types/TextDocumentType.java
60:	private static final String DEFAULT_RESOURCECLASS = "org.sakaiproject.localization.util.TypeProperties";

content-types/src/java/org/sakaiproject/content/types/UrlResourceType.java
55:	private static final String DEFAULT_RESOURCECLASS = "org.sakaiproject.localization.util.TypeProperties";

content-types/src/java/org/sakaiproject/content/types/MakeSitePageAction.java
46:	private static final String DEFAULT_RESOURCECLASS = "org.sakaiproject.localization.util.TypeProperties";
```

2023-02-28 20:10 UTC, jonespm commented on content/content-types/src/webapp/WEB-INF/components.xml
> +	init-method="init" depends-on="org.sakaiproject.localization.util.ContentTypeProperties">
```suggestion
	init-method="init" depends-on="org.sakaiproject.localization.util.TypeProperties">
```

This should be TypeProperties even though its ContentTypeRegistryBean. This service uses some of these classes in content that depend on this class.

2023-03-01 17:56 UTC, ern requested changes
I have a PR coming that addresses the underlying issue with the content types not being managed by spring correctly

2023-03-07 16:15 UTC, jonespm commented
Closing for #11316

2023-03-07 16:15 UTC, closed without merging