SAK-48407 Profile: Takes more steps to update a profile pic
sakaiproject/sakai pull request #11491
Opened 2023-04-21 22:11 UTC by hornersa

The save button needed a data-bs-dismiss to dismiss the modal when saving the change. I also renamed the 'Done' button to 'Cancel'. I found the meaning of the former to be confusing, especially in relation to 'Save'. The button actually cancels without preserving changes made in the modal.

2023-04-26 08:07 UTC, adrianfish requested changes
Thanks Sean. Just a couple of changes with bs3's pull-left -> bs5's float-start.

2023-04-26 08:07 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sui-picture-changer/sui-picture-changer.js
> +          <button class="btn pull-left" data-bs-dismiss="modal" @click=${this._save} ?disabled=${!this.needsSave}>${this.i18n.save}</button>
```suggestion
          <button class="btn float-start" data-bs-dismiss="modal" @click=${this._save} ?disabled=${!this.needsSave}>${this.i18n.save}</button>
```

2023-04-26 08:07 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sui-picture-changer/sui-picture-changer.js
> +          <button class="btn pull-left" data-bs-dismiss="modal">${this.i18n.cancel}</button>
```suggestion
          <button class="btn float-start" data-bs-dismiss="modal">${this.i18n.cancel}</button>
```

2023-05-02 18:46 UTC, hornersa commented
@adrianfish - I've implemented the suggested changes.

2023-05-03 08:31 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sui-picture-changer/sui-picture-changer.js
> +          <button class="btn float-start" @click="${this._remove}">${this.i18n.remove}</button>
```suggestion
          <button class="btn float-end" @click="${this._remove}">${this.i18n.remove}</button>
```

2023-05-03 16:26 UTC, merged