S2U-42 Roster: Card Game - Make card game group aware
sakaiproject/sakai pull request #11698
Opened 2023-06-20 12:29 UTC by stetsche

Only display students to learn in the that are in the same  group

https://sakaiproject.atlassian.net/browse/S2U-42

2023-06-20 13:53 UTC, mpellicer requested changes
I don't think this works for sites without groups, to be honest, can you try a plain site without groups with the patch?

2023-06-20 14:03 UTC, jesusmmp commented
These changes group aware are OK. Tested on my local instance.
Let me test a site without groups

2023-06-20 14:06 UTC, mpellicer commented
> These changes group aware are OK. Tested on my local instance. Let me test a site without groups

I think it fails in site cases. Is this for TAs? Can TAs see all the site members? Not talking about content, I mean MEMBERS.

If an instructor is a member of the site, does not matter how many groups are there, it should see all the students, at the end 
this feature must display the same users that site-manage does.

2023-06-21 09:47 UTC, mpellicer commented
What do you feel about this @jesusmmp ?

2023-06-21 10:00 UTC, mpellicer approved these changes
This sounds nice to me, I think this replicates existing logic in the roster.

2023-06-21 10:01 UTC, jesusmmp commented
> What do you feel about this @jesusmmp ?

Let me test it! :)

2023-06-21 11:59 UTC, jesusmmp commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
> +        String siteId = site.getId();
This siteId should be /site/ + site.getId();

2023-06-21 14:21 UTC, mpellicer approved these changes

2023-06-21 14:22 UTC, mpellicer commented
Let's test all of this in our QA, in sites without groups and sites with groups and TAs.

2023-06-21 14:22 UTC, merged

2023-06-21 14:56 UTC, jesusmmp commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
> +                Set<String> hiddenUsersIds = privacyManager.findHidden(site.getReference(), userIds);
Use siteRef