S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
sakaiproject/sakai pull request #11704
Opened 2023-06-21 12:46 UTC by JuanDavid102

This is linked with https://github.com/sakaiproject/sakai-reference/pull/209

2023-06-21 14:24 UTC, mpellicer requested changes
This requires a conversion script, please link it in sakai-reference

2023-06-21 14:24 UTC, mpellicer commented on rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/model/RWikiObject.java
> +	List getPageGroupsAsList();
Can we define the type? List<String> ?

2023-06-21 14:25 UTC, mpellicer commented on rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/model/RWikiObject.java
> +	void setPageGroupsAsList(List pageGroups);
Can we define the type?

`List<String>`

2023-06-21 14:26 UTC, mpellicer commented on rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWiki.hbm.xml
> +		<set name="pageGroups" table="rwikipagegroups" cascade="all" lazy="false">
Nice!

2023-06-21 14:26 UTC, mpellicer commented on rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWiki.hbm.xml
> +		<set name="pageGroups" table="rwikipagegroups" cascade="all" lazy="false">
We need a conversion script for this.

2023-06-22 06:56 UTC, JuanDavid102 commented on rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/model/RWikiObject.java
> +	List getPageGroupsAsList();
Yes

2023-06-22 07:07 UTC, JuanDavid102 commented
The requested conversion scripts its here: [](https://github.com/sakaiproject/sakai-reference/pull/209)

2023-06-22 09:49 UTC, mpellicer commented
Could you check everything here @bgarciaentornos ? I've almost reviewed it completelly but there are DB changes.

2023-06-22 10:13 UTC, bgarciaentornos approved these changes
I don't find any code issue, LGTM

2023-06-22 10:19 UTC, mpellicer commented
Thanks for all the great work on this.

2023-06-22 10:19 UTC, merged