S2U-42 Card Game: Force 1:1 aspect ratio for image
sakaiproject/sakai pull request #11770
Opened 2023-07-17 11:46 UTC by SirSaibot

Jira: https://sakaiproject.atlassian.net/browse/S2U-42

2023-07-17 12:18 UTC, stetsche requested changes
Looks pretty good, I requested some minor changes. Good job so far!

2023-07-17 12:18 UTC, stetsche commented on library/src/morpheus-master/sass/modules/_b5-polyfill.scss
> +  &.ratio{
could you test this using the scss nesting please?
```
.ratio {
    position: relative;
    width: 100%
    
    & > * {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
    }

    &::before {
        display: block;
        padding-top: var(--bs-aspect-ratio);
        content: "";
    }
}
```

2023-07-17 12:18 UTC, stetsche commented on library/src/morpheus-master/sass/modules/tool/roster/_roster.scss
> +        //keep image from streching when not having 1:1 aspect ratio
```suggestion
        // Keep image from stretching when not having 1:1 aspect ratio
```

2023-07-17 12:18 UTC, stetsche commented on library/src/morpheus-master/sass/modules/tool/roster/_roster.scss
> +        .img-ratio-cover{
spacing
```suggestion
        .img-ratio-cover {
```

2023-07-21 08:09 UTC, stetsche approved these changes
Looks good to me now!

2023-07-21 08:38 UTC, mpellicer commented
Thanks @SirSaibot you're a monster!

2023-07-21 08:38 UTC, merged