SAK-49146 Ignite: Error Cache pesimistic and node fails - TypeImpl
sakaiproject/sakai pull request #11803
Opened 2023-08-02 08:42 UTC by jesusmmp

https://sakaiproject.atlassian.net/browse/SAK-49146

2023-08-03 21:35 UTC, ern approved these changes
There will be db changes needed to drop the version in SAKAI_PERSON_T

Trying to remember if there were other changes needed?

2023-08-04 08:52 UTC, jesusmmp commented
> There will be db changes needed to drop the version in SAKAI_PERSON_T
> 
> Trying to remember if there were other changes needed?

We talked about not drop the version in SAKAI_PERSON_T

Other changes were done here: https://github.com/sakaiproject/sakai/pull/11267/files

2023-08-09 14:14 UTC, ern commented
if you remove the optimistic lock then version column is useless and should be removed.

2023-09-20 15:38 UTC, ern requested changes
Lets discuss this one in the next Core call

2024-06-03 18:32 UTC, ern commented on common/impl/src/java/org/sakaiproject/component/common/type/TypeImpl.hbm.xml
> +    table="CMN_TYPE_T">
```suggestion
    table="CMN_TYPE_T" optimistic-lock="version">
```

2024-06-03 18:32 UTC, ern commented on common/impl/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonImpl.hbm.xml
> +    table="SAKAI_PERSON_T"
```suggestion
    table="SAKAI_PERSON_T" optimistic-lock="version"
```

2024-06-03 18:33 UTC, ern approved these changes

2024-06-03 20:01 UTC, merged