UNIADAPTIVE Work package (s2u-22x)
sakaiproject/sakai pull request #11973
Opened 2023-10-06 09:50 UTC by stetsche

https://sakaiproject.atlassian.net/browse/SAK-49276
https://sakaiproject.atlassian.net/browse/SAK-49337
https://sakaiproject.atlassian.net/browse/SAK-49258

2023-10-06 10:54 UTC, mpellicer commented
Question, how many of these tickets depend on S2U-35? How many of them are bugs that affect 22.x and should be merged via the usual process?

2023-10-10 07:38 UTC, mpellicer commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java
> +        log.info("savedConds {}", savedConditions);
Change any log.info to log.debugs please

2023-10-10 07:50 UTC, mpellicer requested changes
Put some comments in the lines that are producing unexpected results and change some log infos to debugs.

Great job @stetsche , awesome piece of work.

2023-10-10 08:41 UTC, stetsche commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
> +                        resourceEdit.setAvailabilityInstant(false, resourceOpenDate, resourceCloseDate);
TODO: This seems to not work right for some resource types, as the UI does not show the availability correctly

2023-10-10 08:43 UTC, stetsche commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
> +                            .ifPresent(closeDate -> forum.setCloseDate(Date.from(closeDate)));
TODO: Dates do update here, but at least the two availability boolean need to be set. It' might also be necessary to create a new forum, as I observed that when setting it the dates through the UI.

2023-10-10 09:34 UTC, stetsche commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
> +                        resourceEdit.setAvailabilityInstant(false, resourceOpenDate, resourceCloseDate);
```suggestion
                        // TODO: This seems to not work right for some resource types, as the UI does not show the availability correctly
                        resourceEdit.setAvailabilityInstant(false, resourceOpenDate, resourceCloseDate);
```

2023-10-10 09:36 UTC, stetsche commented on webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
> +                    Optional.ofNullable(patchEntity.getOpenDate())
```suggestion
                    // TODO: Dates do update here, but at least the two availability boolean need to be set. It' might also be necessary to create a new forum, as previously observed when setting it the dates through the UI.

                    Optional.ofNullable(patchEntity.getOpenDate())
```

2023-10-10 09:51 UTC, merged

2023-10-10 09:51 UTC, mpellicer commented
Thanks @stetsche terrific work!