SAK-49403: Enhance Log Messages for Improved Turnitin Error Detection
sakaiproject/sakai pull request #12033
Opened 2023-10-25 09:28 UTC by st-manu

[SAK-49403](https://sakaiproject.atlassian.net/browse/SAK-49403)

2023-10-25 10:01 UTC, st-manu commented
@mpellicer @stetsche Could you review this, please? Thank you!

2023-10-25 10:08 UTC, stetsche requested changes
Good job @st-manu! I just added some minor suggestions to make the log even clearer. Please take a look.

2023-10-25 10:08 UTC, stetsche commented on content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
> +				log.error("Unable to fetch site in {}", siteId);
```suggestion
				log.error("Unable to fetch site with id {}", siteId);
```

2023-10-25 10:08 UTC, stetsche commented on content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
> +				log.error("Instructor is null in {}", siteId);
```suggestion
				log.error("Instructor is null. siteId: {}", siteId);
```

2023-10-25 10:08 UTC, stetsche commented on content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
> +				log.error("Unable to fetch user in {}", siteId);
```suggestion
				log.error("Unable to fetch current user on site with id {}", siteId);
```

2023-10-25 10:10 UTC, mpellicer commented
Great job Manu @st-manu

2023-10-25 10:13 UTC, st-manu commented
Thanks @stetsche !!

2023-10-25 10:14 UTC, mpellicer commented
CLA can't be confirmed since the link does not work anymore.

http://licensing.apereo.org/completed-clas

2023-10-25 10:14 UTC, mpellicer commented
@st-manu Do you remember if you signed the ICLA here?

https://www.apereo.org/licensing/agreements/icla

2023-10-25 10:17 UTC, st-manu commented
@mpellicer No, I haven't signed that. I'll sign it now.

2023-10-25 10:36 UTC, stetsche approved these changes

2023-10-26 06:29 UTC, mpellicer commented
CLA confirmed.

2023-10-26 15:19 UTC, merged