S2U-26 Gradebook: support for group instances
sakaiproject/sakai pull request #12127
Opened 2023-11-24 12:26 UTC by bgarciaentornos

2023-11-24 12:37 UTC, jesusmmp commented
Another awesome work!!

2023-12-07 11:53 UTC, bgarciaentornos commented
Small commit after a round of internal testing, more qa needed though

2023-12-11 07:41 UTC, mpellicer commented
Hey, please review some of the codacy issues, they can be improved.

2023-12-11 07:44 UTC, bgarciaentornos commented
I fix a couple Codacy warnings, but the rest were all N-complexity and similar things related to pre-existing code.

2023-12-11 07:44 UTC, mpellicer commented on assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentEventObserver.java
> +                                    org.sakaiproject.service.gradebook.shared.Assignment gradebookAssignment = gradebookService.getAssignmentByNameOrId(event.getContext(), event.getContext(), itemId)
I'm not sure if we should leave a method with two arguments and then the gradebook service call the same method with three arguments, all of this seems very repetitive to me.

2023-12-11 07:46 UTC, mpellicer commented on assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
> +                = gradebookService.getCategoryDefinitions(toGradebookId, toGradebookId);
Same here, I don't know if we should leave this as is and call the method with two arguments when there's only one in the caller.

2023-12-11 07:53 UTC, mpellicer commented on edu-services/gradebook-service/api/src/java/org/sakaiproject/tool/gradebook/facades/Authz.java
> +	public Map findMatchingEnrollmentsForViewableCourseGrade(String gradebookUid, String siteId, int gbCategoryType, String optionalSearchString, String optionalSectionUid);
Needs javadoc update

2023-12-11 07:53 UTC, mpellicer commented on edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
> +  import org.sakaiproject.tool.gradebook.AbstractGradeRecord;
```suggestion
 import org.sakaiproject.tool.gradebook.AbstractGradeRecord;
```

2023-12-11 07:55 UTC, mpellicer commented on edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
> +	protected Set<String> getAllStudentUids(String siteId) {
```suggestion
	protected Set<String> getAllStudentUids(final String siteId) {
```

2023-12-11 07:55 UTC, bgarciaentornos commented
Some context about parameter duplication: previously gradebook instances were linked to a site id, so every method and query regarding permissions, objects or whatever could use the same value. Splitting that between site for permissions and group for gb instance was the hardest bit, deciding where would fit one value or the other on each of the dozens of methods and hundreds of calls.

The scope of this development was limited to providing group support to the gradebook tool, but we realized it would be important to follow this work for external integrations (assignments, samigo, content-review, webservices, lti...). For that reason I created this different jira:
https://sakaiproject.atlassian.net/browse/SAK-49493

The comments about using the same parameter twice is to keep those integrations working as before (gradebok site instances), while moving the code closer to the future version. Both edu-services and gradebookng has lots and lots of similar methods receiving different arguments, called from many different places and doing similar things but not always the same. That was hard to read and to maintain, so I tried to leave it ready so whoever gets that other piece of work doesn't have to go through that process again.

Thanks for the review, I'll work on the other comments/suggestions next!

2023-12-11 08:00 UTC, mpellicer commented on edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
> +	private boolean isUserAbleToViewAssignments(String siteId) {
```suggestion
	private boolean isUserAbleToViewAssignments(final String siteId) {
```

2023-12-11 08:04 UTC, mpellicer commented on edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
> +						log.info("getAllAssignmentGradeRecordsForGbItem No enrollments were specified. Returning an empty List of grade records");
```suggestion
						log.info("getAllAssignmentGradeRecordsForGbItem No enrollments were specified. Returning an empty List of grade records");
```
```suggestion
						log.info("getAllAssignmentGradeRecordsForGbItem: No enrollments were specified. Returning an empty List of grade records");
```

2023-12-11 08:04 UTC, mpellicer commented on edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
> +						log.debug("getAllAssignmentGradeRecordsForGbItems No enrollments were specified. Returning an empty List of grade records");
```suggestion
						log.debug("getAllAssignmentGradeRecordsForGbItems: No enrollments were specified. Returning an empty List of grade records");
```

2023-12-11 08:06 UTC, mpellicer commented on edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
> +		//String siteId = getCurrentSiteId();
Lets remove this

2023-12-11 08:18 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +								for(String member:members){
```suggestion
								for (String member:members) {
```

2023-12-11 08:19 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +									if(siteId!=null && member!=null && securityService.unlock(member, GbPortalPermission.VIEW_OWN_GRADES.getValue(), siteService.siteReference(siteId))){
```suggestion
									if (siteId != null && member != null && securityService.unlock(member, GbPortalPermission.VIEW_OWN_GRADES.getValue(), siteService.siteReference(siteId))) {
```

2023-12-11 08:21 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +					String groupGb = MessageHelper.getString("error.role") + siteService.getSite(siteId).getGroup(gradebookUid).getTitle();
error.role ? Seems weird to me

2023-12-11 08:21 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +					log.error("Error looking up site: {}", siteId, ex);
```suggestion
					log.error("Error looking up site {}: {}", siteId, ex);
```

2023-12-11 08:22 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<Assignment> getGradebookAssignmentsForStudent(final String gUid, final String siteId, final String studentUuid, final SortType sortedBy) {
Rename gUid by 'gradebookUid'

2023-12-11 08:23 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<Assignment> getGradebookAssignments(final String gUid, final String siteId, final SortType sortBy) {
Rename gUid by 'gradebookUid'

2023-12-11 08:23 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<CategoryDefinition> getGradebookCategories(final String gUid, final String siteId) {
Rename gUid by 'gradebookUid'

2023-12-11 08:23 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<CategoryDefinition> getGradebookCategoriesForStudent(String gUid, String siteId, String studentUuid) {
rename gUid by gradebookUid

2023-12-11 08:24 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public Map<String, CourseGrade> getCourseGrades(final String gUid, final String siteId, final List<String> studentUuids, final Map<String, Double> gradeMap) {
gradebookUid

2023-12-11 08:24 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public CourseGrade getCourseGrade(final String gUid, final String siteId, final String studentUuid) {
gradebookUid

2023-12-11 08:25 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public GradeSaveResponse saveGrade(final String gUid, final String siteId, final Long assignmentId, final String studentUuid, final String oldGrade,
gradebookUid

2023-12-11 08:25 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public GradeSaveResponse saveGradesAndCommentsForImport(final String gUid, final String siteId, final Assignment assignment, final List<GradeDefinition> gradeDefList) {
gradebookUid

2023-12-11 08:26 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<GbStudentGradeInfo> buildGradeMatrix(final String gUid, final String siteId, final List<Assignment> assignments,
gradebookUid

2023-12-11 08:26 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<GbStudentGradeInfo> buildGradeMatrixForImportExport(final String gUid, final String siteId, final List<Assignment> assignments, GbGroup groupFilter) throws GbException {
gradebookUid

2023-12-11 08:26 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<GbGradeComparisonItem> buildMatrixForGradeComparison(String gUid, String siteId, Assignment assignment, GradingType gradingType, GradebookInformation settings){
gradebookUid

2023-12-11 08:29 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
> +																		GradebookNgBusinessService businessService, AjaxRequestTarget target, String gUid, String siteId) {
gradebookUid

2023-12-11 08:30 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public void updatePermissionsForUser(final String gUid, final String userUuid, final List<PermissionDefinition> permissions) {
gradebookUid

2023-12-11 08:30 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public void clearPermissionsForUser(final String gUid, final String userUuid) {
gradebookUid

2023-12-11 08:31 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<GbStudentGradeInfo> sortGradeMatrix(String gUid, String siteId, Map<String, GbStudentGradeInfo> matrix, GradebookUiSettings settings) {
gradebookUid

2023-12-11 08:31 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<GbGroup> getSiteSectionsAndGroups(String gUid, String siteId) {
gradebookUid

2023-12-11 08:32 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> -	public void updateAssignmentOrder(final String siteId, final long assignmentId, final int order) {
Update javadoc

2023-12-11 08:33 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public void updateAssignmentCategorizedOrder(final String gUid, final String siteId, final long assignmentId, final int order)
Update javadoc

2023-12-11 08:33 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +			log.error(String.format("Gradebook %s not found", gUid));
```suggestion
			log.error("Gradebook {} not found", gUid);
```

2023-12-11 08:34 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +			log.error(String.format("GradebookAssignment %d not found in gradebook %s", assignmentId, gUid));
```suggestion
			log.error("GradebookAssignment {} not found in gradebook {}", assignmentId, gUid);
```

2023-12-11 08:34 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public List<GbGradeCell> getEditingNotifications(final String gradebookUid, final String siteId, final Date since) {
update javadoc

2023-12-11 08:34 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public Assignment getAssignment(final String gUid, final String siteId, final long assignmentId) {
gradebookUid and update javadoc

2023-12-11 08:35 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public Assignment getAssignment(final String gUid, final String siteId, final String assignmentName) {
gradebookUid and javadoc

2023-12-11 08:35 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public int getAssignmentSortOrder(final String gUid, final String siteId, final long assignmentId) {
gradebookUid and javadoc

2023-12-11 08:36 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public void updateAssignment(final String gUid, final String siteId, final Assignment assignment) {
gradebookUid and javadoc

2023-12-11 08:36 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public boolean updateUngradedItems(final String gUid, final String siteId, final long assignmentId, final String grade, final GbGroup group) {
gradebookUid and javadoc

2023-12-11 08:36 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public String getAssignmentGradeComment(final String gUid, final long assignmentId, final String studentUuid) {
gradebookUid and javadoc

2023-12-11 08:37 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public String getAssignmentExcuse(final String gUid, final long assignmentId, final String studentUuid){
gradebookUid

2023-12-11 08:37 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public boolean updateAssignmentGradeComment(final String gUid, final String siteId, final long assignmentId, final String studentUuid,
gradebookUid and javadoc

2023-12-11 08:37 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> +	public GbRole getUserRoleOrNone(String siteId) {
javadoc

2023-12-11 08:40 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java
> +		final String gUid = (String) params.get("gUid");
arerrrrggggggggggggggg

2023-12-11 10:09 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
> +							group);//
Remove this empty comment

2023-12-11 10:11 UTC, mpellicer commented on gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
> +		final List<GbGroup> groups = this.businessService.getSiteSectionsAndGroups(currentGradebookUid, currentSiteId);//igual quitar opcion all y filtros
put the comment in a different line but in English

2023-12-11 10:18 UTC, mpellicer commented on portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
> +		return groupIds.contains(gbGroup) ? true : false;
```suggestion
		return groupIds.contains(gbGroup);
```

2023-12-11 10:18 UTC, mpellicer commented on portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
> +				if (thisTool && unHidden && checkGradebookVisibility) allowPage = true;
```suggestion
allowPage = thisTool && unHidden && checkGradebookVisibility;
```

2023-12-11 10:19 UTC, mpellicer commented on site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
> +                        if (toolId.equals("sakai.gradebookng")) {
```suggestion
                        if ("sakai.gradebookng".equals(toolId)) {
```

2023-12-11 10:20 UTC, mpellicer commented on site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
> +                        if (toolId.equals("sakai.gradebookng")) {
create a const for "sakai.gradebookng" and use it here and the sentence below.

2023-12-11 10:21 UTC, mpellicer commented on site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/GradebookGroupEnabler.java
> +	 * @return true if the context was modified
But it returns false in all cases!

2023-12-11 10:24 UTC, mpellicer commented on site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
> +			} else if (choice.equals("sakai.gradebookng")) {
```suggestion
			} else if ("sakai.gradebookng".equals(choice)) {
```

2023-12-11 10:25 UTC, mpellicer commented on site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
> +				List<String> selectedGroups = isGroupType ? (List<String>)state.getAttribute("selectedGroups") : new ArrayList<>();
Create a constant for "selectedGroups", and another one for "gb-group"

2023-12-11 10:26 UTC, mpellicer commented on site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
> +				List<String> selectedGroups = isGroupType ? (List<String>)state.getAttribute("selectedGroups") : new ArrayList<>();
SELECTED_GROUPS_ATTRIBUTE
GB_GROUP_PROPERTY

2023-12-11 10:27 UTC, mpellicer commented on site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
> +						if (toolId.equals("sakai.gradebookng") && isGroupType) {
SAKAI_GRADEBOOK_ID.equals(toolId)

2023-12-11 10:28 UTC, mpellicer commented on site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
> +				} else if (id.endsWith("sakai.gradebookng")) {
id.endsWith(SAKAI_GRADEBOOK_TOOL_ID), a new constant.

2023-12-11 10:32 UTC, mpellicer requested changes
This is an excellent piece of work.

It is complex, risky, and modifies many tools, it will require big testing of both gradebook for site and groups, and does not introduce data loss risks if this gets reverted.

Required many changes most of them about naming, documentation and good software practices.

GREAT job @bgarciaentornos

2023-12-12 09:28 UTC, mpellicer approved these changes

2023-12-12 09:28 UTC, merged