SAK-49520 CKEditor: Added FMath plugin
sakaiproject/sakai pull request #12150
Opened 2023-11-30 10:27 UTC by mpellicer

Would be good to release this as a Sakai Webjar like other plugins, but I don't know how to do it.

2023-12-13 13:34 UTC, bgarciaentornos approved these changes

2023-12-13 17:52 UTC, jonespm requested changes
I talked to @mpellicer on Slack about how to re-package this as a webjar and said I'd be available to help get this in if needed.

2023-12-15 10:12 UTC, mpellicer commented
@jonespm Thanks! I've moved the 5K files to a webjar and now this is a very simple PR.

This should be broken until the webjar is released and pushed into Maven central, I've verified it locally:
![image](https://github.com/sakaiproject/sakai/assets/8653754/a028c640-0c23-415c-8805-44fecd8fc549)

It is not enabled by default, you need to compile Sakai with '-Dckeditor-fmath' flag to enable it, like the accessibility plugin does.

2023-12-15 10:21 UTC, bgarciaentornos commented
Much better like this, thanks @jonespm

2023-12-20 08:51 UTC, merged