SAK-49581 T&Q: Added sharing permissions to QPs
sakaiproject/sakai pull request #12210
Opened 2023-12-20 15:21 UTC by mpellicer

2023-12-20 16:13 UTC, mpellicer commented on samigo/samigo-app/src/webapp/jsf/questionpool/sharePool.jsp
> +<h4><h:outputText value="#{questionPoolMessages.members_without_access} \"#{questionpoolshare.questionPoolName}\" "/></h4>
False positive

2023-12-20 16:14 UTC, mpellicer commented on samigo/samigo-app/src/webapp/jsf/questionpool/accesstype_whatsThis.jsp
> +            <h2 class="western">
false positive

2023-12-20 16:15 UTC, mpellicer commented on samigo/samigo-app/src/webapp/jsf/questionpool/previewQuestion.jsp
> +<h3><h:outputText value="#{questionPoolMessages.t_previewQuestion}"/></h3>
false positive

2023-12-20 16:15 UTC, mpellicer commented on samigo/samigo-app/src/webapp/jsf/questionpool/sharePool.jsp
> +<h4><h:outputText value="#{questionPoolMessages.members_with_access} \"#{questionpoolshare.questionPoolName}\" "/></h4>
false positive

2023-12-27 12:14 UTC, bgarciaentornos requested changes
This is a tough one to review! Found a couple things I'd like to know more about but nothing outstanding...

2024-01-08 07:50 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/converter/AccessTypeConverter.java
> +            case "31":
Okay

2024-01-08 07:57 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
> +  	public void setQpDataModelByLevel(String sortProperty, boolean sortAscending) {
Probably copy/pasta from 13 years ago, you are right

2024-01-08 08:16 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
> -  	public void setQpDataModelByLevelCopy(String sortProperty, boolean sortAscending) {
It is redundant I think

2024-01-08 08:16 UTC, mpellicer commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
> +  	public void setQpDataModelByLevel(String sortProperty, boolean sortAscending) {
Done, I've reverted these changes, the bean attributes are being used.

2024-01-08 08:30 UTC, mpellicer commented
I'll do another round of testing focused on sorting QPs by columns.

2024-01-08 08:53 UTC, mpellicer commented
> I'll do another round of testing focused on sorting QPs by columns.

@bgarciaentornos Sorting still works after reverting the changes about the unused params.

![zz](https://github.com/sakaiproject/sakai/assets/8653754/b03745ad-eaae-44d6-afd9-0dec3510cefb)

2024-01-08 08:54 UTC, bgarciaentornos approved these changes
Nice, thanks!

2024-01-08 09:38 UTC, merged

2024-01-08 09:39 UTC, mpellicer commented
Thank you very much for the review