SAK-49519 Accessibility: Address insufficient color contrast issues with text/links on Gateway page
sakaiproject/sakai pull request #12223
Opened 2023-12-26 10:29 UTC by kunaljaykam

https://sakaiproject.atlassian.net/browse/SAK-49519

2023-12-27 13:31 UTC, bgarciaentornos requested changes
Thanks, just a couple spacing issues

2023-12-27 13:31 UTC, bgarciaentornos commented on library/src/webapp/content/gateway/about.html
> +    color: #0e4466;
Fix spacing

2023-12-27 13:31 UTC, bgarciaentornos commented on library/src/webapp/content/gateway/acknowledgements.html
> +	}
Fix spacing

2023-12-27 13:31 UTC, bgarciaentornos commented on library/src/webapp/content/gateway/features.html
> +    	background-color: #0e4466;
Fix spacing

2023-12-28 08:37 UTC, kunaljaykam commented
> Thanks, just a couple spacing issues

Thanks for noticing.

2024-01-03 12:00 UTC, bgarciaentornos approved these changes
Thanks for addressing the issues!

2024-01-08 21:36 UTC, merged