S2 u 5 master
sakaiproject/sakai pull request #12241
Opened 2024-01-04 15:17 UTC by stetsche

Draft due to:
- Dependency on #12233
- A missing fix

Conversion scripts: #234

https://sakaiproject.atlassian.net/browse/S2U-5

2024-01-08 08:16 UTC, bgarciaentornos requested changes
Thanks, a few minor things related to the S2U-5 commit.

NOTE: This other fix will also have to be incorporated

2024-01-08 08:16 UTC, bgarciaentornos commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
> +customElements.define("sakai-rubric-association", SakaiRubricAssociation);
EOF

2024-01-08 08:20 UTC, stetsche commented on rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java
> +        log.info("itemId {}, rubricId {}", itemId, rubricId);
I'd prefer to remove it

2024-01-08 08:22 UTC, stetsche commented on samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
> +    <script src="/library/webjars/jquery-ui/1.12.1/jquery-ui.min.js"></script>
Yes, I needed to add it for the modal dialog to work

2024-01-08 08:23 UTC, stetsche commented
Thanks @bgarciaentornos! I will make the adjustments and cherry-pick the other fix when I rebase after S2U-32/28 is merged.

2024-01-19 12:28 UTC, stetsche commented
I applied the fixes and rebased onto master. When Build is passing, this should be ready to go!

2024-01-23 11:49 UTC, mpellicer approved these changes
This is awesome, terrific job @stetsche and @bgarciaentornos.

Merging this after #11789 as we agreed.

2024-01-23 11:49 UTC, merged