S2U-14 5.1.1.10 T&Q: Canceled questions and score re-calculation
sakaiproject/sakai pull request #12279
Opened 2024-01-16 16:32 UTC by V100X

Jira [S2U-14](https://sakaiproject.atlassian.net/browse/S2U-14)
Developed by: @stetsche

This is a port from Sakai 22 to 24

From PRs: (#11328) (#11542)

2024-01-16 17:06 UTC, mpellicer commented
Please could you add a reference PR for the conversion scripts ?

2024-01-16 17:06 UTC, mpellicer requested changes
conversion scripts needed.

2024-01-16 17:16 UTC, mpellicer approved these changes
Thanks for the hard work @V100X and @stetsche

2024-01-17 07:11 UTC, mpellicer requested changes
Seems that @stetsche has spotted a bug present on this, can you explain it Markus? Is it affecting 22.x ?

2024-01-17 08:24 UTC, mpellicer commented
Thank you very much for reporting it!

2024-01-17 12:05 UTC, V100X commented
Should be ready now 👍

2024-01-17 12:06 UTC, stetsche commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java
> +}
```suggestion
}

```

2024-01-17 12:11 UTC, stetsche commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java
> +}
```suggestion
}
```

2024-01-17 12:25 UTC, stetsche approved these changes
Yeah, looks all good now, well done @V100X!

2024-01-17 12:31 UTC, mpellicer approved these changes
Awesome! thanks for the effort guys

2024-01-17 13:30 UTC, merged