Improve dark mode compatibility in iframe & Samigo opening in new tab
sakaiproject/sakai pull request #12323
Opened 2024-01-30 15:29 UTC by kunaljaykam

https://sakaiproject.atlassian.net/browse/SAK-48845

**WIP**

2024-02-06 10:32 UTC, adrianfish requested changes
Seems decent to me, thanks. Just a few small things.

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/headscripts.js
> +		htmlElement.classList.forEach((className) => {
You don't need to add parentheses around single lambda arguments. We don't do that in Java either. The linting rules for the webcomponents will complain about unnecessary parens.

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/portal/portal.theme.switcher.js
> +  portal.darkThemeSwitcher && portal.darkThemeSwitcher.setAttribute("aria-checked", onOff.toString());
You can use optional chaining here.
portal.darkThemeSwitcher?.setAttribute

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/portal/portal.theme.switcher.js
> +  if (portal.user && portal.user.id) {
portal?.user?.id

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/portal/portal.theme.switcher.js
> +        localStorage.setItem('sakai-theme', theme); // save the theme to local storage
I don't think you need this comment. It's pretty obvious what's happening :)

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/portal/portal.theme.switcher.js
> +  let themeToApply = (portal.isOsDarkThemeSet() ? portal.darkThemeClass : portal.lightThemeClass);
```suggestion
  let themeToApply = portal.isOsDarkThemeSet() ? portal.darkThemeClass : portal.lightThemeClass;
```

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/portal/portal.theme.switcher.js
> +    if (portal.user && portal.user.id && portal.userTheme === portal.defaultThemeClass) {
```suggestion
    if (portal?.user?.id && portal.userTheme === portal.defaultThemeClass) {
```

2024-02-06 10:32 UTC, adrianfish commented on library/src/webapp/js/portal/portal.theme.switcher.js
> +
```suggestion
```

2024-02-06 10:32 UTC, adrianfish commented on portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
> +			boolean themeEnabled = ServerConfigurationService.getBoolean("portal.themes", true);
You can use PortalConstants.PROP_PORTAL_THEMES

2024-02-06 11:54 UTC, kunaljaykam commented
> Seems decent to me, thanks. Just a few small things.

I added all the changes you requested. Thank you!

2024-02-08 16:27 UTC, adrianfish approved these changes

2024-02-08 16:27 UTC, merged