SAK-50029 WC SakaiGrades obfuscate grades on default page load
sakaiproject/sakai pull request #12573
Opened 2024-05-06 22:19 UTC by ern

https://sakaiproject.atlassian.net/browse/SAK-50029

2024-05-06 22:23 UTC, ern commented
Sample view when page loads, clicking anywhere on the grades will reveal (remove blur) grades.
<img width="367" alt="image" src="https://github.com/sakaiproject/sakai/assets/209420/2d09966b-7399-4111-b467-bba36c876391">

2024-05-07 11:00 UTC, adrianfish requested changes

2024-05-07 11:00 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js
> +    secret: { type: Boolean },
```suggestion
    secret: { type: Boolean },
    _i18n: { state: true },
```

2024-05-07 11:00 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js
> +    secret: { type: Boolean },
I always put the actual attributes first, and the state (private) type stuff afterwards.

2024-05-07 11:00 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js
> +    if (this.secret) {
```suggestion

    if (this.secret) {
```

2024-05-07 11:00 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js
> +            filter: blur(3px);
```suggestion
          filter: blur(3px);
```

2024-05-07 11:00 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-widgets/src/SakaiGradesWidget.js
>          site-id="${ifDefined(this.siteId ? this.siteId : undefined)}"
```suggestion
      <sakai-grades
        user-id="${ifDefined(this.userId)}"
        site-id="${ifDefined(this.siteId)}"
        secret
```

2024-05-08 21:21 UTC, ern commented
Updated screenshot
<img width="367" alt="image" src="https://github.com/sakaiproject/sakai/assets/209420/fe8f2e05-1b65-42ae-b868-77beb54491d0">

2024-05-09 22:04 UTC, merged