SAK-50326 Prevent frequent webcomponents build failures
sakaiproject/sakai pull request #12753
Opened 2024-07-24 21:48 UTC by hornersa

Jira: https://sakaiproject.atlassian.net/browse/SAK-50326

Attached to the jira are three out of many frequent examples where I've encountered build failures with webcomponents/tool/pom.xml during the 'npm install' step. These have occurred since the changes introduced with SAK-50230. Since introducing the proposed changes which force the npm cache to be clearnd, I've not experienced any further build failures due to the npm install step. (The additional time it takes to execute this extra step of clearing the npm's cache is negligible, in my experience.)

2024-07-25 14:37 UTC, ern commented on webcomponents/tool/pom.xml
> +                        </configuration>
@hornersa I would tie this to the clean phase so that when perform `mvn clean` it will run.

2024-07-25 14:38 UTC, ern requested changes
There are 4 places where we use the frontend plugin so we should also add it to those as well

2024-08-01 16:17 UTC, ern commented
Sean quick question could it be your simply not running the clean goal?
`mvn clean install`

2024-08-01 21:52 UTC, hornersa commented
@ern - No, clean and install are always invoked when I run maven. Re the other suggestions for the pom file, I'll need to get back to that. (Currently in the thick of troubleshooting LTI/OAuth issues with a vendor.)

2024-08-16 20:09 UTC, hornersa commented
If others (having for instance similar Red Hat distros like Oracle Linux) encounter the problem in the associated jira, we can revisit this then at that time. In the meantime, I'm closing this PR (per a conversation w/ Earle today).

2024-08-16 20:09 UTC, closed without merging