SAK-44225 SakaiGrader keep the selected submission
sakaiproject/sakai pull request #12887
Opened 2024-09-12 13:24 UTC by st-manu

After thoroughly testing the previous PR, I found that with the change, the selected student is lost, and the first one is set by default. Similarly (as was already happening), when changing groups, the displayed student is not retained if they are in the group being filtered.

2024-09-18 10:28 UTC, st-manu commented on webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
> +      const currentSubmissionId = this._submission.id;
@adrianfish thank you for your comment. I'm updating the commit.

2024-09-19 15:41 UTC, adrianfish requested changes
Just a small change :)

2024-09-19 15:41 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
> +      if (currentSubmission) {
```suggestion
      if (filtered.some(s => s.id === this._submission.id)) {
```

2024-09-19 15:41 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
> +      if (currentSubmission) {
No need for the variable at all :)

2024-09-19 15:41 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
> +      const currentSubmission = filtered.find(s => s.id === this._submission.id);
```suggestion
```

2024-09-20 09:31 UTC, st-manu commented
@adrianfish thank you for the suggestions!

2024-09-20 10:59 UTC, adrianfish approved these changes
Thanks for this work. It's good to see other people doing work in the grader. It's a complicated piece of code.

2024-09-23 15:23 UTC, merged