SAK-46120 lessons Show notifications when comments added
sakaiproject/sakai pull request #12898
Opened 2024-09-19 15:11 UTC by adrianfish

https://sakaiproject.atlassian.net/browse/SAK-46120

2024-09-23 15:29 UTC, ern requested changes

2024-09-23 15:29 UTC, ern commented on kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java
> +                    e.printStackTrace();
prefer a log message here vs printStackTrace

2024-09-23 15:29 UTC, ern commented on lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/api/AddLessonsCommentUserNotificationHandler.java
> +                        bhEvents.add(new UserNotificationData(from, to, context, "Lessons Comment", url, LessonBuilderConstants.TOOL_ID));
if "Lessons Comment" is a key then prefer something like "lessons-comment"

2024-09-24 14:10 UTC, adrianfish commented on kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java
> +                    e.printStackTrace();
lol.

2024-09-25 13:31 UTC, ern commented on lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/service/SimplePageToolService.java
> +        log.info("Initializing Lesson Builder Tool");
```suggestion
        log.debug("Initializing Lessons Simple Page Tool Service");
```

2024-09-25 13:32 UTC, ern commented on lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/service/SimplePageToolService.java
> +                log.info("Completed Lesson Builder DDL");
```suggestion
                log.debug("Completed Lesson Builder DDL");
```

2024-09-25 13:34 UTC, ern approved these changes

2024-09-26 12:04 UTC, merged