SAK-50636 Profile missing preferences.image.message property
sakaiproject/sakai pull request #13068
Opened 2024-11-29 20:46 UTC by ottenhoff

2024-11-30 02:00 UTC, ern approved these changes

2024-12-02 07:48 UTC, bgarciaentornos requested changes
There were other languages with this property in the original commit where this property was removed, could you please also add them back? Thanks

2024-12-26 20:07 UTC, ottenhoff commented
Okay @bgarciaentornos, added the other old configs

2024-12-27 07:18 UTC, bgarciaentornos approved these changes
Thanks!

2024-12-27 21:00 UTC, merged