SAK-50725 Tests & Quizzes: Calculated Question fails if the @ character exists in the text
sakaiproject/sakai pull request #13074
Opened 2024-12-02 12:30 UTC by st-manu

https://sakaiproject.atlassian.net/browse/SAK-50725

Test & Quizzes fail when a calculated question contains an @ symbol in the question body used for something other than a global variable.

2024-12-02 12:34 UTC, jesusmmp approved these changes

2024-12-02 14:47 UTC, ottenhoff requested changes
Please add a test! There are lots of tests already in place and patterns you can repeat.

2024-12-03 12:26 UTC, st-manu commented
test added ✅ @ottenhoff

2024-12-03 15:11 UTC, ottenhoff approved these changes
Awesome job with the tests!!

2024-12-03 21:11 UTC, merged