SAK-50735 Gradebook fix student summary print view
sakaiproject/sakai pull request #13089
Opened 2024-12-06 15:43 UTC by ottenhoff

2024-12-08 07:28 UTC, kunaljaykam requested changes
the css changes are missing

2024-12-09 14:42 UTC, ottenhoff commented
> the css changes are missing

I don't know what you're referring to

2024-12-09 14:59 UTC, kunaljaykam commented on gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
> +    const $head = $iframe.contents().find("head");
does replacing `var` with `const` solves the issue?

2024-12-09 15:16 UTC, ottenhoff commented
> I tested it locally. I got multiple blank pages with tables but no data. Is that expected?

No, that's the broken behavior.

2024-12-09 16:27 UTC, ottenhoff commented
yeah idk what's going on here! closing

2024-12-09 16:27 UTC, closed without merging