SAK-44040: FORUMS: While grading appears 'rubricsEventHandlers is not defined'
sakaiproject/sakai pull request #8498
Opened 2020-08-31 11:47 UTC by jesusmmp

2020-08-31 11:48 UTC, jesusmmp commented
@adrianfish, please could you take a look? rubricsEventHandlers function is not defined.
Do we need it? Thanks!

2020-08-31 13:23 UTC, adrianfish requested changes
There's a commented out function in forums.js. You should remove that as well.

2020-09-01 06:02 UTC, jesusmmp commented
> There's a commented out function in forums.js. You should remove that as well.

Just updated!

2020-09-01 14:28 UTC, adrianfish approved these changes

2020-09-01 14:28 UTC, merged