SAK-44306: Error on log when trying to upload file with no file selected
sakaiproject/sakai pull request #8589
Opened 2020-09-18 09:02 UTC by FerAlvarez95

2020-09-21 10:16 UTC, jesusmmp commented
@jonespm FerAlvarez95 signed the cla some months ago.

2020-09-21 10:18 UTC, jesusmmp commented
@adrianfish, we have a lot of errors on the log since this one (https://jira.sakaiproject.org/browse/SAK-40906)
was introduced. Please, could you take a look? Thanks!

2020-09-22 15:16 UTC, ern requested changes

2020-09-22 15:16 UTC, ern commented on samigo/samigo-app/src/java/com/corejsf/UploadRenderer.java
> +            log.debug("Failed to get upload part from request. Null will be returned.", e);
log.warn("Failed to get upload part from request, NULL will be returned, {}", e.toString());

2020-09-22 15:16 UTC, ern commented on samigo/samigo-app/src/java/com/corejsf/UploadRenderer.java
> +            log.debug("Failed to get upload part from request. Null will be returned.", e);
```suggestion
            log.warn("Failed to get upload part from request, NULL will be returned, {}", e.toString());
```

2020-09-22 18:30 UTC, merged