SAK-44341 - escape the filename before building the resourceId for th…
sakaiproject/sakai pull request #8627
Opened 2020-09-29 00:51 UTC by maurercw

…e check to see if it exists or not

2020-09-29 13:16 UTC, bjones86 approved these changes

2020-09-29 15:33 UTC, ern requested changes

2020-09-29 15:33 UTC, ern commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
> +					resourceId = collectionName +"/"+ Validator.escapeResourceName(uploadFileName);
Validator is deprecated try using FormattedText

2020-09-29 15:33 UTC, ern commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
> +					resourceId = resourceGroup + Validator.escapeResourceName(uploadFileName);
Validator is deprecated try using FormattedText

2020-09-29 19:13 UTC, maurercw commented
@ern I used Validator since that's already used (heavily) in that class.  I wanted everything to work exactly the same way as when it first creates the file.

2020-09-29 23:55 UTC, maurercw commented
Looking into it a bit, there's no suitable replacement for escapeResourceName.  I'd also imagine that the tool would be super wonky if a different escaping mechanism was used down the road after resources were already created under the current mechanism.  You need to be able to rebuild the resourceId in a reliable way.  So, my vote is to continue with the status quo of the deprecated method.  Plus, it's only been deprecated since December 2011.  ;)

2020-10-18 22:57 UTC, maurercw commented
I suppose I could move the escapeResourceName method over to the FormattedText service, but that seems like it's out of scope for this change as other tools that use it would be impacted.  If there was a suitable method already there, I'd happily use it.

2020-10-20 18:26 UTC, ern approved these changes

2020-10-20 18:26 UTC, merged