SAK-44433 Samigo fix score adjustment validation on question totals page
sakaiproject/sakai pull request #8685
Opened 2020-10-13 14:07 UTC by curtisvo

Remove jsf double validation because it fails on comma, add validation on save to QuestionScoreUpdateListener.

2020-10-13 14:09 UTC, curtisvo commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreUpdateListener.java
> -    	  if (bean.getPublishedAssessment() != null
This is already done earlier in the method and repeated here. Since bean hasn't changed it can be removed.

2020-10-14 19:47 UTC, bjones86 requested changes
@curtisvo, there's a conflict here now. Do you mind updating?

2020-11-09 19:39 UTC, curtisvo commented
I just resolved the conflict by reverting part of SAK-44371, it no longer makes sense to specify a validatorMessage on the question score page since after this change the number validation is done in the UpdateListener.

After this change, adjustments to total scores and individual question scores are validated the same way. I hadn't noticed that the student results page also allows adjustment, but I just tested and it works fine with commas in french.

2020-11-10 14:04 UTC, bjones86 submitted a review, later dismissed

2020-11-10 14:04 UTC, bjones86 commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
> +    List<String> badAdjList = new ArrayList<String>();
```suggestion
    List<String> badAdjList = new ArrayList<>();
```

2020-11-10 14:04 UTC, bjones86 commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreUpdateListener.java
> +  	  List<String> badAdjList = new ArrayList<String>();
```suggestion
  	  List<String> badAdjList = new ArrayList<>();
```

2020-11-10 14:06 UTC, bjones86 requested changes

2020-11-10 14:06 UTC, bjones86 commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreUpdateListener.java
> +  	  List<String> badAdjList = new ArrayList<String>();
```suggestion
  	  List<String> badAdjList = new ArrayList<>();
```

2020-11-10 14:06 UTC, bjones86 commented on samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
> +    List<String> badAdjList = new ArrayList<String>();
```suggestion
    List<String> badAdjList = new ArrayList<>();
```

2020-11-10 14:07 UTC, bjones86 commented
Thanks, @curtisvo. Looks good, just two minor things

2020-11-10 15:19 UTC, bjones86 commented
@curtisvo, I would commit these changes for you, but I think you haven't checked the box to "allow edits from maintainers", or whatever that thing is called!

2020-11-11 15:57 UTC, curtisvo commented
> @curtisvo, I would commit these changes for you, but I think you haven't checked the box to "allow edits from maintainers", or whatever that thing is called!

Done! I can't find that option now, maybe because I pushed the branch to hec-montreal's repo.

2020-11-11 16:00 UTC, bjones86 approved these changes
No worries, thanks for the contribution @curtisvo!

2020-11-11 17:36 UTC, merged