SAK-44262 Fix rubrics table creation in Oracle
sakaiproject/sakai pull request #8692
Opened 2020-10-15 03:43 UTC by davidpbauer

rbc_rubric and rbc_criterion were not getting automatically created in Oracle
because the columnDefinition configuration there previously was not compatitble.
This removes that property and instead sets the default values with PrePersist
JPA annotation.

2020-10-15 13:34 UTC, ottenhoff approved these changes

2020-10-15 15:24 UTC, ern requested changes
While PrePersist is an alternative it will not update the DDL the way that columnDefinition does. It would be preferable to have this on the ddl vs the default managed by code.

2020-10-15 15:24 UTC, ern commented on rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Criterion.java
> +    }
Formatting needs to follow the existing style

2020-10-15 15:24 UTC, ern commented on rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rubric.java
> +    }
Formatting needs to follow existing style

2020-10-15 15:31 UTC, ern commented
The other interesting issue here is these fields have defaults assigned to them already via code.

2020-10-15 16:08 UTC, davidpbauer commented
Oops, sorry about the code style. I've updated the commit to match what's there.

2020-10-15 16:21 UTC, davidpbauer commented
My interpretations was the the default value assigned to the fields is just an initial value for the field in Java. The code could later set the field back to null which could be persisted defeating the idea behind a default value in the database. The PrePersist is then needed for those cases where the code set the field to null and is trying to persist to the database. It would ensure the null value is never saved for a new record regardless of the column definition in the table. So, I would think we'd want both to start the field with the default value in the code and make sure that when a new record is persisted the value is set to the default if it has somehow changed to null. There is also a PreUpdate which could do the same thing when updating the records.

I do realize that this doesn't actually set the default value in the database column, but I haven't found a way to set a default value in the DDL using these annotations that works in both MySQL and Oracle for either double or boolean datatypes. Any ideas?

2020-10-15 17:42 UTC, ern commented
@davidpbauer I looked into this a bit and it maybe related to the use of attributes, see https://stackoverflow.com/questions/16078681/what-properties-does-column-columndefinition-make-redundant

Basically using columnDefinition overrides Hibernates auto generated DDL and makes many of the attributes redundant. Unfortunately columnDefinition is the only way to specify a default value in the ddl.

`
    @Column(columnDefinition = "double default 0 not null")
    private Double weight = 0D;
`

2020-10-15 17:54 UTC, ern commented
You can try turning on hibernate SQL logging and look at the DDL statements with:
`hibernate.show_sql=true`
in sakai.properties

2020-10-20 15:42 UTC, ern approved these changes

2020-10-20 18:05 UTC, merged