SAK-44531 Permissions widget: Undo Changes button not always clickable
sakaiproject/sakai pull request #8732
Opened 2020-10-23 09:47 UTC by bgarciaentornos

2020-10-23 10:59 UTC, adrianfish requested changes
can you move that inline style into libary?

2020-10-23 10:59 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/sakai-permissions.js
> +        <div class="permissions-undo-button"" style="padding-top:.5em">
It would be better to move this into library.
tool/authz/_authz.scss

2020-10-23 11:10 UTC, bgarciaentornos commented
> can you move that inline style into libary?

Done

2020-10-26 13:24 UTC, ern approved these changes

2020-11-03 16:40 UTC, adrianfish approved these changes

2020-11-04 13:35 UTC, merged