SAK-44561 Error parsing the date/time PA SYSTEM Create Banner
sakaiproject/sakai pull request #8751
Opened 2020-10-27 14:20 UTC by MRutea

2020-10-29 18:47 UTC, adrianfish requested changes
See what you think about my comment.

2020-10-29 18:47 UTC, adrianfish commented on pasystem/pasystem-tool/tool/src/webapp/scripts/pasystem-tool.js
> -              $("[name='" + $datepicker.attr('id') + "_selected_datetime']").val("");
I wouldn't just remove this, unless you know exactly where it's used. It looks like it's the hidden field generated by the date picker. I'd play it safe and do:
const hidden = this.querySelector(`[name='${$datepicker.attr('id')}_selected_datetime']`);
hidden && hidden.value = "";

2020-10-30 08:28 UTC, MRutea commented
@adrianfish 
Hi, Adrian;

Thanks for your comment.
I think the line was no longer used, after the different tests I did.
That's why I removed it.

But you're right.
Let's play safe. I added the code you wrote for me.

Thanks again.

2020-10-30 12:33 UTC, adrianfish approved these changes
Good to go, as long as you tested my suggested change - just in case :)

2020-11-02 09:00 UTC, merged