SAK-43760 Rubrics: Can not use keyboard-only to edit criterion or rating
sakaiproject/sakai pull request #8763
Opened 2020-11-02 12:09 UTC by MRutea

SAK-43760 Rubrics: Can not use keyboard-only to edit criterion or rating

SAK-43760 Rubrics: Can not use keyboard-only to edit criterion or rating

2020-11-02 13:32 UTC, adrianfish requested changes

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
> + openEditWithKeyboard(e){
Can you stick to the formatting in the rest of the file? Space before the opening brace and a blank line to start the function body, unless the function is only one line of code.

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
> +    if(e.keyCode == 32 || e.keyCode == 32 ){
Did you mean to check two codes here? And, could you leave a space after the if, and one before the opening brace?

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
> +
Could you take this blank line out?

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js
> + openEditWithKeyboard(e){
Could you format this function in line with the rest of the file? And, I think you meant to test two different codes here.

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-rating-edit.js
> + openEditWithKeyboard(e){
Please format this like the rest of the file. And, you're checking for 32 twice.

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
> + openEditWithKeyboard(e){
Can you format this like the rest of the file, please? Also, you're checking for the same keycode twice.

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
> +    const classType = e.target.className;
use classlist for this:
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
> +    const weighted = 'weighted';
Why bother with a const for a string you're only going to use once? Just use the string.

2020-11-02 13:32 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
> +    const clone = 'clone';
Same with all these variables. You don't need them.

2020-11-03 08:58 UTC, MRutea commented
@adrianfish 
Hello Adrian.
Thanks again for your comments.
I will be more careful with those details.
I have made the corrections that you suggest.

2020-11-03 15:10 UTC, adrianfish commented
@MRutea I'm a bit pedantic about the formatting, sorry! I'm really glad you're working on these rubrics tickets.

2020-11-03 15:12 UTC, adrianfish approved these changes
GTG. Thanks for making those changes.

2020-11-03 15:18 UTC, merged