SAK-44597 Rubrics: Error in console sorting rubrics
sakaiproject/sakai pull request #8764
Opened 2020-11-02 13:01 UTC by MRutea

SAK-44597 Rubrics: Error in console sorting rubrics

2020-11-02 15:50 UTC, adrianfish requested changes

2020-11-02 15:50 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
> +    if (sortInput === "") {
Why not get rid of that toString on sortInput. className is always a string. Also, you can just go if (!sortInput). Empty strings are falsy in JS.
https://developer.mozilla.org/en-US/docs/Web/API/Element/className

2020-11-02 15:50 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
>      const rubric = sortInputValue.split('-');
I'd just go:
const rubricClass = sortInput && sortInput.toLowerCase().split("-")[0];
You don't even need the falsy test, then.

2020-11-03 11:03 UTC, MRutea commented
@adrianfish 
Hi, Adrian;
Thanks for your comments.
I've made the necessary changes.
But finally I think it is convenient to keep the "if" conditional, since I think it adequately prevents possible errors in the successive lines.

Thanks again.

2020-11-03 15:25 UTC, adrianfish requested changes

2020-11-03 15:25 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
> +    const rubricType = sortInput.toLowerCase().split("-")[1];
const sortInput = event.target.className.toLowerCase();
(see https://developer.mozilla.org/en-US/docs/Web/API/Element/className. className always returns a string)

...

const [rubricClass, rubricType] = sortInput.split("-");
(see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

const query = `.${sortInput}.sort-element-${rubricClass}`;

2020-11-03 16:02 UTC, MRutea commented
@adrianfish 
Hi, Adrian;
Changes made.

I didn't know about "Destructuring assignment" in js.
Thank you again.

2020-11-03 16:05 UTC, adrianfish approved these changes
GTG

2020-11-04 13:35 UTC, merged