SAK-44486 Forums - email notification is sent to users who didn't par…
sakaiproject/sakai pull request #8769
Opened 2020-11-03 01:02 UTC by austin48

…ticipate in conversation

2020-11-30 22:03 UTC, ern requested changes

2020-11-30 22:03 UTC, ern commented on msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
> +					if (log.isDebugEnabled()){
Use the newer log pattern please!

2020-12-01 00:53 UTC, austin48 commented on msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
> +					if (log.isDebugEnabled()){
done

2020-12-03 00:10 UTC, ern commented on msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
> +					}
```suggestion
					log.debug("The author: {} wants to be notified", threadauthor);
```

2020-12-03 00:11 UTC, ern approved these changes

2020-12-03 13:16 UTC, merged