Forums will not accept rubric scores with 3+ decimals
sakaiproject/sakai pull request #8840
Opened 2020-11-25 08:55 UTC by josecebe

2020-11-25 10:37 UTC, adrianfish requested changes
You need to add the SAK number to the commit.

2020-11-25 10:37 UTC, adrianfish commented on msgcntr/messageforums-app/src/webapp/js/forum.js
> +      $(rubricGrading).find('input').each(function() {
rubricGrading && rubricGrading.querySelectorAll("input").forEach(i => i.prop("disabled", true));

2020-11-25 10:37 UTC, adrianfish commented on msgcntr/messageforums-app/src/webapp/js/forum.js
> +      $(rubricGrading).find('input').each(function() {
What are you disabling here? Is it the score override boxes?

2020-11-25 10:52 UTC, adrianfish commented on msgcntr/messageforums-app/src/webapp/js/forum.js
> +      $(rubricGrading).find('input').each(function() {
If it is the comment boxes, you should probably be more specific
"input.fine-tune-points"

2020-11-25 12:49 UTC, adrianfish commented
The rubric is accepting more than 2 decimal places everywhere, and this is wrong. Try it in assignments. I think this PR should be closed and the JIRA should be rewritten to reflect this. This is a regression, basically.

2020-11-26 09:14 UTC, josecebe commented
> The rubric is accepting more than 2 decimal places everywhere, and this is wrong. Try it in assignments. I think this PR should be closed and the JIRA should be rewritten to reflect this. This is a regression, basically.

Hi @adrianfish , in forums it is not working as expected (you can check it in the video attached in JIRA ticket). The rubric webcomponent is inside a form on this tool, so disabling these inputs it's just a trick to avoid these inputs to be validated using the forums form originally criteria.

2020-11-26 09:59 UTC, adrianfish commented
@josecebe But if you actually fix the rubric and stop it accepting more than 2dp, then it will work everywhere. That way you are fixing the underlying issue, not the symptom.

2020-11-26 10:23 UTC, josecebe commented
@adrianfish I see what you say, I thought it was the correct behaviour to allow more than 2 decimals. I'm going to work on a proper solution.

2020-11-26 10:40 UTC, adrianfish commented
@josecebe I'm pretty sure that was the behaviour, just allowing 2 d.p. I think something may have broken that. Take a look at the rating code in the actual rubrics manager parts. I don't think that allows more than 2 dp, so hopefully that's still working. Thanks for looking at it.

2021-01-12 16:04 UTC, ern commented
@josecebe can you resolve the conflicts

2021-09-30 11:31 UTC, mpellicer commented
Closing and unassigning @josecebe

2021-09-30 11:31 UTC, closed without merging