SAK-44901: SAMIGO - Importing ZIP with a xml file
sakaiproject/sakai pull request #9004
Opened 2021-02-04 12:44 UTC by jesusmmp

2021-03-09 15:34 UTC, adrianfish commented on samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ImportService.java
> +	    			log.error("Unable to mkdir " + dir.getPath());
log.error("Unable to mkdir {}", dir.getPath());

2021-03-09 15:36 UTC, adrianfish commented on samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ImportService.java
> +	    						log.error("Unable to mkdir " + dir.getPath() + "/" + dirName);
I'd move dir.getPath() + "/" + dirName into a variable called directory. It's used up above and you'll then just be able to write:
log.error("Unable to mkdir {}", directory);

2021-03-09 15:38 UTC, adrianfish commented on samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ImportService.java
> +	    				log.error("Error parsing imsmanifest.xml: " + e.getMessage());
log.error("Error parsing imsmanifest.xml: {}", e.getMessage(), e);

2021-03-09 15:40 UTC, adrianfish commented on samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ImportService.java
> +	public String getQtiFilename() {
Why bother doing this? You may as well just use Lombok.

2021-06-01 13:52 UTC, bjones86 requested changes
Changes requested, as per Adrian's review.

2022-11-10 17:28 UTC, ern approved these changes

2022-11-11 03:16 UTC, ern approved these changes

2022-11-11 03:17 UTC, merged