SAK-45166 Adjust font size of Assignments Honor Pledge
sakaiproject/sakai pull request #9143
Opened 2021-03-26 12:40 UTC by V100X

2021-03-26 13:32 UTC, V100X commented
![SAK-45166](https://user-images.githubusercontent.com/81161239/112638951-11a4db80-8e40-11eb-83af-d0d0fb7facee.png)

2021-03-26 13:54 UTC, mpellicer commented
Hi @V100X , would you mind signing in this ICLA? 

https://www.apereo.org/licensing/agreements/icla

It's the individual contributor license agreement.

Thanks

2021-03-29 09:19 UTC, josecebe requested changes

2021-03-29 09:19 UTC, josecebe commented on library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_jumbotron.scss
> +    font-size: $default-font-size;
Now "$jumbotron-font-size" variable is unused, maybe its new value should be $default-font-size?

2021-03-29 09:19 UTC, josecebe commented on library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
> -			font-size: $jumbotron-heading-font-size;
Maybe "$jumbotron-heading-font-size" new value should be $font-size-h4?

2021-03-29 09:20 UTC, josecebe commented on library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
> -			font-size: $jumbotron-heading-font-size;
After the change, check other places where $jumbotron-heading-font-size is used

2021-03-30 11:52 UTC, josecebe approved these changes
LGTM

2021-04-20 15:59 UTC, ern approved these changes

2021-04-20 15:59 UTC, merged