SAK-45266 fixing hardcoded CSS in portal for Dark Mode
sakaiproject/sakai pull request #9145
Opened 2021-03-29 01:20 UTC by wyu12

https://jira.sakaiproject.org/browse/SAK-45266

2021-03-30 15:12 UTC, profmikegreene requested changes

2021-03-30 15:12 UTC, profmikegreene commented on portal/portal-charon/charon/src/webapp/styles/portalstyles.css
> +	background-color: var(--sakai-background-color-4);
```suggestion
	background-color: var(--sakai-background-color-2);
```

2021-03-30 15:12 UTC, profmikegreene commented on portal/portal-charon/charon/src/webapp/styles/portalstyles.css
> +	/*background-color:#F0F0F0;*/
```suggestion
```

2021-05-24 14:31 UTC, ern approved these changes

2021-05-24 14:31 UTC, merged