SAK-45465 Spacing issue on topic settings page in Forums tool
sakaiproject/sakai pull request #9274
Opened 2021-05-21 09:12 UTC by victorfv2

I have changed the align-self attribute to margin-top because having the banner inside the label when you try to centre the check-box it looks wrong

2021-05-25 11:06 UTC, josecebe approved these changes

2021-06-01 05:34 UTC, fostersdesign requested changes
@victorfv2 , this doesn't address the second part of the issue: the spacing between the Availability radio buttons and the labels.

2021-06-03 02:07 UTC, fostersdesign requested changes

2021-06-03 02:07 UTC, fostersdesign commented on library/src/morpheus-master/sass/base/_defaults.scss
> +	margin-right: 10px;
This change affects too many elements throughout Sakai. 

How about a more-specific change in _forums.scss, such as adding:
```
.Mrphs-sakai-forums #revise input[type="radio"] {
 margin: 0 4px;
}
```
And changing:
```
.Mrphs-sakai-forums #revise .checkbox input[type="checkbox"], .Mrphs-sakai-forums #revise .checkbox .Mrphs-sakai-samigo .dataTables_wrapper .dataTables_paginate > a.paginate_button[type="checkbox"], .Mrphs-sakai-samigo .dataTables_wrapper .Mrphs-sakai-forums #revise .checkbox .dataTables_paginate > a.paginate_button[type="checkbox"], .Mrphs-sakai-forums #revise .checkbox .Mrphs-sakai-samigo #authorIndexForm\:remove-selected.disabled[type="checkbox"], .Mrphs-sakai-samigo .Mrphs-sakai-forums #revise .checkbox #authorIndexForm\:remove-selected.disabled[type="checkbox"] {
- margin: 0 10px;
+ margin: 0 4px;
}
.Mrphs-sakai-forums #revise .checkbox input[type="checkbox"] + label, .Mrphs-sakai-forums #revise .checkbox .Mrphs-sakai-samigo .dataTables_wrapper .dataTables_paginate > a.paginate_button[type="checkbox"] + label, .Mrphs-sakai-samigo .dataTables_wrapper .Mrphs-sakai-forums #revise .checkbox .dataTables_paginate > a.paginate_button[type="checkbox"] + label, .Mrphs-sakai-forums #revise .checkbox .Mrphs-sakai-samigo #authorIndexForm\:remove-selected.disabled[type="checkbox"] + label, .Mrphs-sakai-samigo .Mrphs-sakai-forums #revise .checkbox #authorIndexForm\:remove-selected.disabled[type="checkbox"] + label {
- padding-left: 10px;
+ padding-left: 4px;
}
```

2021-06-03 02:07 UTC, fostersdesign commented on library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
> +			margin-top: 1.2em;
```suggestion
			margin-top: 1em;  // to match the label top margin
			align-self: flex-start;
```

2021-09-30 11:28 UTC, mpellicer commented
Closing and unassigning @victorfv2

2021-09-30 11:28 UTC, closed without merging