SAK-45517 - signup jsf upgrade
sakaiproject/sakai pull request #9303
Opened 2021-05-28 00:15 UTC by maurercw

2021-06-03 14:41 UTC, bjones86 requested changes
LGTM, just some minor issues

2021-06-03 14:41 UTC, bjones86 commented on signup/tool/src/webapp/js/signupScript.js
> +            }
spacing is a little off here

2021-06-03 14:41 UTC, bjones86 commented on signup/tool/src/webapp/js/signupScript.js
> +            }
and here

2021-06-03 14:41 UTC, bjones86 commented on signup/tool/src/webapp/js/signupScript.js
> +            }
and here

2021-06-14 01:23 UTC, maurercw commented on signup/tool/src/webapp/js/signupScript.js
> +            }
should be fixed

2021-06-14 01:23 UTC, maurercw commented on signup/tool/src/webapp/js/signupScript.js
> +            }
should be fixed

2021-06-14 01:23 UTC, maurercw commented on signup/tool/src/webapp/js/signupScript.js
> +            }
should be fixed

2021-06-17 14:30 UTC, ern approved these changes

2021-06-24 13:14 UTC, bjones86 approved these changes

2021-06-24 13:14 UTC, merged