SAK-43480 - Filtering wrong decimal separator characters in the new G…
sakaiproject/sakai pull request #9373
Opened 2021-06-15 10:39 UTC by danielmerino

…rader respecting to user's locale

2021-06-15 12:23 UTC, danielmerino commented
Codacy is rejecting a change with this error: "Found non-literal argument to RegExp Constructor".

I need that rule to be disabled, because the regexp argument is dynamically built. AFAIK there's no other option but disabling it, at least in this patch.

2021-06-17 14:28 UTC, ern commented
Would using [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) be ideal?

2021-06-18 10:17 UTC, danielmerino commented
> Would using [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) be ideal?

Sorry, Earle, I don't understand. Intl.NumberFormat would be useful for parsing a number, but that number is what user is entering in the grade field.

The case we are detecting here is when some user with an specific locale is typing the grade using a decimal separator wrong for his locale. Having that the wrong decimal separator is a valid thousand separator in each locale, I can't imagine how NumberFormat could help.

The existing code filters all non-valid characters typed in the field. I have just added the correct decimal separator to the accepted characters.

2021-06-18 14:40 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
> -    } else if (!e.key.match(/[\d.,]/)) {
I know I'm a little late to this, but don't we just need a + after the closing ]?
/[\d.,]+/

All your change seems to be doing is making the decimal character more specific, based on the portal locale, whereas we should just be able to accept all of the decimal chars.

2021-06-18 15:00 UTC, adrianfish commented
Try doing this in gradeSelected

this.submission.grade = this.submission.grade.replace(",",".");

2021-06-18 15:22 UTC, adrianfish requested changes
I get your change now! You're just blocking any decimal point/comma input that's not valid for the current locale. Nice. I've just made your change a bit more compact.

2021-06-18 15:22 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
> +    var rgxp = new RegExp(i18nDecimalPattern);
const decimalSeparator = (1.1).toLocaleString(portal.locale).substring(1, 2);
const rgxp = new RegExp(`[\\d${decimalSeparator}]`);

2021-06-18 15:22 UTC, adrianfish commented on webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
> +  }
You don't need this function

2021-06-22 12:36 UTC, danielmerino commented
Hi @adrianfish unfortunately I'm going on holidays today and I won't be able to do your requested changes until middle of July.

If you want to change the commit and merge it, I don't mind if you give to yourself the authory. Otherwise, I will do it when I return. Thanks.

2021-06-22 13:13 UTC, adrianfish commented
Hi @danielmerino No worries, I'll do that. I'll add a commit so we'll both be on it. Thanks for the change, and enjoy your break. I hope you do something nice :)

2021-06-22 14:08 UTC, adrianfish approved these changes

2021-06-22 14:08 UTC, merged