SAK-45734 Rewrite the 'Account Validator Tool' from RSF to Thymeleaf.
sakaiproject/sakai pull request #9695
Opened 2021-08-27 13:09 UTC by V100X

· Set Thymeleaf as template engine.
· Improve UI.

More info and **Testing Doc** on: [Jira SAK-45735](https://jira.sakaiproject.org/browse/SAK-45734)

2021-08-30 05:18 UTC, mpellicer requested changes
This needs a Jira description and presents conflicts.

2021-08-30 05:38 UTC, mpellicer requested changes
I stopped after 48 comments.

This PR needs many format changes related to spacing, extra spaces, tabs, etc.

Please fix all the patterns found and re-request a review.

Fix the conflicts, provide a right description for the commit and the Github PR.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/model/ValidationAccount.java
> +        @JsonIgnore
tabs vs spaces

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/nbactions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I don't think this file is needed, remove it from the PR.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +    private Locale userLocale;
I don't like defining this variables at the controler, define and use them at request level, no problem having the same pattern again and again.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        if (tokenId == null || "".equals(tokenId)) {
StringUtils.isBlank(tokenId)

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        // } checks left:
Remove this comment.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            return "error.html";
Create a ERROR_TEMPLATE variable and use the variable for all the error.html templates.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        // Fill from:
Delete comment and spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            if (!"".equals(serverConfigurationService.getString("account-validator.terms"))) {
Tabs vs spaces.

Use a variable and StringUtils.
String accountValidatorTerms = serverConfigurationService.getString("account-validator.terms");
if (StringUtils.isNotBlank(accountValidatorTerms)) .....

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +                String termsText = serverConfigurationService.getString("account-validator.terms");
This is not needed anymore if we use a variable here.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        // getValidationAccount {
Remove this.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        if (tokenId == null || "".equals(tokenId)) {
Use StringUtils and spacing.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            return "error.html";
use the ERROR_TEMPLATE variable instead

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing and use the variable

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing and use a variable.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +                return "error.html";
Use variable.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing and use a variable for validate.html template.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            return "error.html";
Use a variable here.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        // Fill from:
Remove this comment

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        return "passwordReset";
Use a template variable here.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +    String passResForm(HttpServletRequest req, HttpServletResponse response, Model model, @RequestBody String requestForm,
Can we have a more descriptive method name?

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        if (tokenId == null || "".equals(tokenId)) {
Use StringUtils.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            return "error.html";
template variable.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing and variable name.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing and variable.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing and use a template variable.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +                        existingSites.add(groupId);
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            Iterator<String> git = groups.iterator();
I don't think we need an iterator here, you can loop a set:

for (String groupRef : groups)

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +            List existingSites = new ArrayList<>();
Define the type, List<String>

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +                model.addAttribute("welcome", messageSource.getMessage("validate.welcome.single", new String[]{uiService}, userLocale));
You can use one line here:

model.addAttribute("welcome", messageSource.getMessage(existingSites.size() >= 2 ? "validate.welcome.plural" : "validate.welcome.single", new String[]{uiService}, userLocale));

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +        if (!"".equals(serverConfigurationService.getString("account-validator.terms"))) {
Same as above with this, use a variable and StringUtils, do not call serverConfigurationService.getString two times.

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +
Spacing

2021-08-30 05:38 UTC, mpellicer commented on reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/controller/MainController.java
> +                    } catch (UserNotDefinedException e) {
Use multicatch here:
catch (UserNotDefinedException | UserPermissionException  | UserLockedException | UserAlreadyDefinedException   e) {

https://docs.oracle.com/javase/8/docs/technotes/guides/language/catch-multiple.html

2021-09-14 13:37 UTC, mpellicer commented
What's the state of this PR? Is it ready for review?

It presents conflicts right now.

2021-09-14 15:45 UTC, V100X commented
> What's the state of this PR? Is it ready for review?
> 
> It presents conflicts right now.

Conflict solved. It is ready for review.

2021-09-15 11:54 UTC, mpellicer commented
I tested locally and doesn't work for me, when I'm trying to verify my account throws a JS error:
![image](https://user-images.githubusercontent.com/8653754/133428727-38874380-785e-4fc0-b30b-e81df7bded73.png)

2021-09-15 12:18 UTC, mpellicer requested changes

2021-09-15 12:18 UTC, mpellicer commented on reset-pass/account-validator-tool/src/webapp/content/templates/newUser.html
> +                var terms = "false";
Use let

2021-09-27 22:56 UTC, ern commented
Really good stuff Vincent

I noticed a lot of repetition in the css you think we could consolidate that? Even better would be to just uses css from morpheus, vs the local css here.

2021-09-28 09:21 UTC, mpellicer approved these changes

2021-09-28 09:44 UTC, merged