SAK-46280 Forums : fix encoding for mailtos
sakaiproject/sakai pull request #9854
Opened 2021-09-22 09:20 UTC by bgarciaentornos

Not possible to solve using the existing component EscapedOutputLinkRenderer (there's another encoding afterwards), so removing it.

Adding missing i18n too

2021-09-27 14:24 UTC, adrianfish requested changes

2021-09-27 14:24 UTC, adrianfish commented on msgcntr/messageforums-app/src/webapp/js/forum.js
> +    });
```suggestion
    document.querySelectorAll("[id*=createEmail1").forEach(item => {
        item.setAttribute('href', item.href.replaceAll('+', ' '));
    });
```

2021-09-27 14:24 UTC, adrianfish commented on msgcntr/messageforums-app/src/webapp/js/forum.js
> +    });
Actually, shouldn't you just use setAttribute and getAttribute, or do you want to do the replace on the absolute url?

2021-09-27 21:19 UTC, ern requested changes
Don't you think it would be better to fix the issue that is  creating the markup incorrectly?

2021-09-28 07:42 UTC, bgarciaentornos commented
That's how it was done previously with the EscapedOutputLinkRenderer class, but now with this jsf version I couldn't find a way.

2021-09-29 08:04 UTC, mpellicer approved these changes

2021-09-29 08:04 UTC, merged