SAK-45967: No bullhorn notification when clicking post for assi…
sakaiproject/sakai pull request #9863
Opened 2021-09-27 10:54 UTC by JKJANETSCHEK

...gnment that was draft

2021-09-27 13:50 UTC, adrianfish requested changes

2021-09-27 13:50 UTC, adrianfish commented on assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
> +            if (newAssignment ||(!a.getDraft() && !newAssignment)) {
```suggestion
            if (newAssignment || !a.getDraft()) {
```

2021-09-28 08:29 UTC, JKJANETSCHEK commented
Thank you for your input. I committed your suggested changes.
Best regards

2021-09-28 14:07 UTC, adrianfish approved these changes

2021-09-29 09:32 UTC, merged