SAK-45992: Fixed Bullhorn Notification for group assignment with futu…
sakaiproject/sakai pull request #9864
Opened 2021-09-27 13:22 UTC by JKJANETSCHEK

…re open date

2021-09-27 13:40 UTC, adrianfish requested changes

2021-09-27 13:40 UTC, adrianfish commented on assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
> +                                if(!(openTime.isAfter(Instant.now()))){
Same here. I'd use isBefore

2021-09-28 08:44 UTC, JKJANETSCHEK commented
Thanks, i have changed it to openTime.isBefore.
Best regards

2021-09-28 13:54 UTC, adrianfish approved these changes

2021-09-29 09:54 UTC, merged